parameters:
    database_host: localhost
    database_port: 3306
    database_name: ace_app
    database_user: root
    database_password: ~
    app_name: asd

    membros_visibility: true
    membros_label: Gestãozera

    disciplinas_visibility: true
    disciplinas_label: 'Disc'

    eventos_visibility: true
    eventos_label: 'Eventos'
