/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.ace.acedsl.acedsl.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage
 * @generated
 */
public class AcedslSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static AcedslPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AcedslSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = AcedslPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case AcedslPackage.APLICATIVO:
      {
        Aplicativo aplicativo = (Aplicativo)theEObject;
        T result = caseAplicativo(aplicativo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.SEPARACAO_DISCIPLINAS:
      {
        SeparacaoDisciplinas separacaoDisciplinas = (SeparacaoDisciplinas)theEObject;
        T result = caseSeparacaoDisciplinas(separacaoDisciplinas);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.ORGANIZACAO_CURSO:
      {
        OrganizacaoCurso organizacaoCurso = (OrganizacaoCurso)theEObject;
        T result = caseOrganizacaoCurso(organizacaoCurso);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.ORGANIZACAO_DEPARTAMENTO:
      {
        OrganizacaoDepartamento organizacaoDepartamento = (OrganizacaoDepartamento)theEObject;
        T result = caseOrganizacaoDepartamento(organizacaoDepartamento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.SECAO_EVENTOS:
      {
        SecaoEventos secaoEventos = (SecaoEventos)theEObject;
        T result = caseSecaoEventos(secaoEventos);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.SECAO_MEMBROS:
      {
        SecaoMembros secaoMembros = (SecaoMembros)theEObject;
        T result = caseSecaoMembros(secaoMembros);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.SECAO_DISCIPLINAS:
      {
        SecaoDisciplinas secaoDisciplinas = (SecaoDisciplinas)theEObject;
        T result = caseSecaoDisciplinas(secaoDisciplinas);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.SECAO_NOTICIAS:
      {
        SecaoNoticias secaoNoticias = (SecaoNoticias)theEObject;
        T result = caseSecaoNoticias(secaoNoticias);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.ESTILO:
      {
        Estilo estilo = (Estilo)theEObject;
        T result = caseEstilo(estilo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.LISTA_CURSOS:
      {
        ListaCursos listaCursos = (ListaCursos)theEObject;
        T result = caseListaCursos(listaCursos);
        if (result == null) result = caseSeparacaoDisciplinas(listaCursos);
        if (result == null) result = caseOrganizacaoDepartamento(listaCursos);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.LISTA_DISCIPLINAS:
      {
        ListaDisciplinas listaDisciplinas = (ListaDisciplinas)theEObject;
        T result = caseListaDisciplinas(listaDisciplinas);
        if (result == null) result = caseSeparacaoDisciplinas(listaDisciplinas);
        if (result == null) result = caseOrganizacaoCurso(listaDisciplinas);
        if (result == null) result = caseOrganizacaoDepartamento(listaDisciplinas);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.LISTA_DEPARTAMENTOS:
      {
        ListaDepartamentos listaDepartamentos = (ListaDepartamentos)theEObject;
        T result = caseListaDepartamentos(listaDepartamentos);
        if (result == null) result = caseSeparacaoDisciplinas(listaDepartamentos);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.LISTA_PERIODOS:
      {
        ListaPeriodos listaPeriodos = (ListaPeriodos)theEObject;
        T result = caseListaPeriodos(listaPeriodos);
        if (result == null) result = caseSeparacaoDisciplinas(listaPeriodos);
        if (result == null) result = caseOrganizacaoCurso(listaPeriodos);
        if (result == null) result = caseOrganizacaoDepartamento(listaPeriodos);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.CURSO:
      {
        Curso curso = (Curso)theEObject;
        T result = caseCurso(curso);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.DEPARTAMENTO:
      {
        Departamento departamento = (Departamento)theEObject;
        T result = caseDepartamento(departamento);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case AcedslPackage.PERIODO:
      {
        Periodo periodo = (Periodo)theEObject;
        T result = casePeriodo(periodo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Aplicativo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Aplicativo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAplicativo(Aplicativo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Separacao Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Separacao Disciplinas</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSeparacaoDisciplinas(SeparacaoDisciplinas object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Organizacao Curso</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Organizacao Curso</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOrganizacaoCurso(OrganizacaoCurso object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Organizacao Departamento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Organizacao Departamento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOrganizacaoDepartamento(OrganizacaoDepartamento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Secao Eventos</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Secao Eventos</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSecaoEventos(SecaoEventos object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Secao Membros</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Secao Membros</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSecaoMembros(SecaoMembros object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Secao Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Secao Disciplinas</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSecaoDisciplinas(SecaoDisciplinas object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Secao Noticias</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Secao Noticias</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSecaoNoticias(SecaoNoticias object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Estilo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Estilo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEstilo(Estilo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Lista Cursos</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Lista Cursos</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListaCursos(ListaCursos object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Lista Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Lista Disciplinas</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListaDisciplinas(ListaDisciplinas object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Lista Departamentos</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Lista Departamentos</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListaDepartamentos(ListaDepartamentos object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Lista Periodos</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Lista Periodos</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListaPeriodos(ListaPeriodos object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Curso</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Curso</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCurso(Curso object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Departamento</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Departamento</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDepartamento(Departamento object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Periodo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Periodo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePeriodo(Periodo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //AcedslSwitch
