/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.ace.acedsl.acedsl.Aplicativo

@RunWith(XtextRunner)
@InjectWith(AceDslInjectorProvider)
class AceDslParsingTest{

	@Inject
	ParseHelper<Aplicativo> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
