/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.ui.contentassist;

import org.xtext.ace.acedsl.ui.contentassist.AbstractAceDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AceDslProposalProvider extends AbstractAceDslProposalProvider {
}
