/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl;

import org.xtext.ace.acedsl.AceDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AceDslStandaloneSetup extends AceDslStandaloneSetupGenerated {
  public static void doSetup() {
    AceDslStandaloneSetup _aceDslStandaloneSetup = new AceDslStandaloneSetup();
    _aceDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
