/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl;

import org.xtext.ace.acedsl.AbstractAceDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AceDslRuntimeModule extends AbstractAceDslRuntimeModule {
}
