<?php

namespace AceBundle\Repository;

/**
 * DisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param integer $list_id
     * @return null|string
     */
    public function getListTitle ($list_id)
    {
        $title = null;
        switch($list_id)
        {
            @@@title_cases@@@
        }
        return $title;
    }
}
