<?php

namespace AceBundle\Repository;

/**
 * MembroGestaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembroGestaoRepository extends \Doctrine\ORM\EntityRepository
{
}
