/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.ace.acedsl.ui.internal.AcedslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AceDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AcedslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AcedslActivator.getInstance().getInjector(AcedslActivator.ORG_XTEXT_ACE_ACEDSL_ACEDSL);
	}
	
}
