/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAceDslScopeProvider extends DelegatingScopeProvider {
}
