<?php

namespace AceBundle\Repository;

/**
 * DisciplinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplinaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param integer $list_id
     * @return null|string
     */
    public function getListTitle ($list_id)
    {
        $title = null;
        switch($list_id)
        {
            /*@@@title_cases@@@*/
            case 1:
                $title = 'PSI - Primeiro Semestre'; break;
            case 2:
                $title = 'PSI - Segundo Semestre'; break;
            case 3:
                $title = 'PCS - Computação Cooperativo - Quinto Quadrimestre'; break;
            case 4:
                $title = 'PCS - Computação Cooperativo - Sexto Quadrimestre'; break;
            case 5:
                $title = 'PCS - Computação Semestral'; break;
        }
        return $title;
    }
}
