/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.validation;

import org.xtext.ace.acedsl.validation.AbstractAceDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AceDslValidator extends AbstractAceDslValidator {
}
