/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.ace.acedsl.acedsl.AcedslFactory;
import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.Aplicativo;
import org.xtext.ace.acedsl.acedsl.Curso;
import org.xtext.ace.acedsl.acedsl.Departamento;
import org.xtext.ace.acedsl.acedsl.Estilo;
import org.xtext.ace.acedsl.acedsl.Fonte;
import org.xtext.ace.acedsl.acedsl.ListaCursos;
import org.xtext.ace.acedsl.acedsl.ListaDepartamentos;
import org.xtext.ace.acedsl.acedsl.ListaDisciplinas;
import org.xtext.ace.acedsl.acedsl.ListaPeriodos;
import org.xtext.ace.acedsl.acedsl.OrganizacaoCurso;
import org.xtext.ace.acedsl.acedsl.OrganizacaoDepartamento;
import org.xtext.ace.acedsl.acedsl.Periodo;
import org.xtext.ace.acedsl.acedsl.SecaoDisciplinas;
import org.xtext.ace.acedsl.acedsl.SecaoEventos;
import org.xtext.ace.acedsl.acedsl.SecaoMembros;
import org.xtext.ace.acedsl.acedsl.SecaoNoticias;
import org.xtext.ace.acedsl.acedsl.SeparacaoDisciplinas;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AcedslPackageImpl extends EPackageImpl implements AcedslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass aplicativoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass separacaoDisciplinasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass organizacaoCursoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass organizacaoDepartamentoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secaoEventosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secaoMembrosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secaoDisciplinasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass secaoNoticiasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass estiloEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaCursosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaDisciplinasEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaDepartamentosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass listaPeriodosEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass cursoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass departamentoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass periodoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fonteEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private AcedslPackageImpl()
  {
    super(eNS_URI, AcedslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link AcedslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static AcedslPackage init()
  {
    if (isInited) return (AcedslPackage)EPackage.Registry.INSTANCE.getEPackage(AcedslPackage.eNS_URI);

    // Obtain or create and register package
    AcedslPackageImpl theAcedslPackage = (AcedslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof AcedslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new AcedslPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theAcedslPackage.createPackageContents();

    // Initialize created meta-data
    theAcedslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theAcedslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(AcedslPackage.eNS_URI, theAcedslPackage);
    return theAcedslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getAplicativo()
  {
    return aplicativoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAplicativo_Nome()
  {
    return (EAttribute)aplicativoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getAplicativo_Url()
  {
    return (EAttribute)aplicativoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAplicativo_SecaoEventos()
  {
    return (EReference)aplicativoEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAplicativo_SecaoMembros()
  {
    return (EReference)aplicativoEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAplicativo_SecaoDisciplinas()
  {
    return (EReference)aplicativoEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAplicativo_SecaoNoticias()
  {
    return (EReference)aplicativoEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getAplicativo_Estilo()
  {
    return (EReference)aplicativoEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSeparacaoDisciplinas()
  {
    return separacaoDisciplinasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOrganizacaoCurso()
  {
    return organizacaoCursoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getOrganizacaoDepartamento()
  {
    return organizacaoDepartamentoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecaoEventos()
  {
    return secaoEventosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecaoEventos_Nome()
  {
    return (EAttribute)secaoEventosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecaoMembros()
  {
    return secaoMembrosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecaoMembros_Nome()
  {
    return (EAttribute)secaoMembrosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecaoDisciplinas()
  {
    return secaoDisciplinasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecaoDisciplinas_Nome()
  {
    return (EAttribute)secaoDisciplinasEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSecaoDisciplinas_SeparacaoDisciplinas()
  {
    return (EReference)secaoDisciplinasEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSecaoNoticias()
  {
    return secaoNoticiasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecaoNoticias_Nome()
  {
    return (EAttribute)secaoNoticiasEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSecaoNoticias_Facebook()
  {
    return (EAttribute)secaoNoticiasEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEstilo()
  {
    return estiloEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEstilo_Logo()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEstilo_Fonte()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEstilo_CorPrimaria()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEstilo_CorSecundaria()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEstilo_CorTerciaria()
  {
    return (EAttribute)estiloEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getListaCursos()
  {
    return listaCursosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getListaCursos_Curso()
  {
    return (EReference)listaCursosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getListaDisciplinas()
  {
    return listaDisciplinasEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getListaDepartamentos()
  {
    return listaDepartamentosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getListaDepartamentos_Departamento()
  {
    return (EReference)listaDepartamentosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getListaPeriodos()
  {
    return listaPeriodosEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getListaPeriodos_Periodo()
  {
    return (EReference)listaPeriodosEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCurso()
  {
    return cursoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCurso_Nome()
  {
    return (EAttribute)cursoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCurso_OrganizacaoCurso()
  {
    return (EReference)cursoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDepartamento()
  {
    return departamentoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDepartamento_Nome()
  {
    return (EAttribute)departamentoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDepartamento_OrganizacaoDepartamento()
  {
    return (EReference)departamentoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPeriodo()
  {
    return periodoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPeriodo_Nome()
  {
    return (EAttribute)periodoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getFonte()
  {
    return fonteEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AcedslFactory getAcedslFactory()
  {
    return (AcedslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    aplicativoEClass = createEClass(APLICATIVO);
    createEAttribute(aplicativoEClass, APLICATIVO__NOME);
    createEAttribute(aplicativoEClass, APLICATIVO__URL);
    createEReference(aplicativoEClass, APLICATIVO__SECAO_EVENTOS);
    createEReference(aplicativoEClass, APLICATIVO__SECAO_MEMBROS);
    createEReference(aplicativoEClass, APLICATIVO__SECAO_DISCIPLINAS);
    createEReference(aplicativoEClass, APLICATIVO__SECAO_NOTICIAS);
    createEReference(aplicativoEClass, APLICATIVO__ESTILO);

    separacaoDisciplinasEClass = createEClass(SEPARACAO_DISCIPLINAS);

    organizacaoCursoEClass = createEClass(ORGANIZACAO_CURSO);

    organizacaoDepartamentoEClass = createEClass(ORGANIZACAO_DEPARTAMENTO);

    secaoEventosEClass = createEClass(SECAO_EVENTOS);
    createEAttribute(secaoEventosEClass, SECAO_EVENTOS__NOME);

    secaoMembrosEClass = createEClass(SECAO_MEMBROS);
    createEAttribute(secaoMembrosEClass, SECAO_MEMBROS__NOME);

    secaoDisciplinasEClass = createEClass(SECAO_DISCIPLINAS);
    createEAttribute(secaoDisciplinasEClass, SECAO_DISCIPLINAS__NOME);
    createEReference(secaoDisciplinasEClass, SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS);

    secaoNoticiasEClass = createEClass(SECAO_NOTICIAS);
    createEAttribute(secaoNoticiasEClass, SECAO_NOTICIAS__NOME);
    createEAttribute(secaoNoticiasEClass, SECAO_NOTICIAS__FACEBOOK);

    estiloEClass = createEClass(ESTILO);
    createEAttribute(estiloEClass, ESTILO__LOGO);
    createEAttribute(estiloEClass, ESTILO__FONTE);
    createEAttribute(estiloEClass, ESTILO__COR_PRIMARIA);
    createEAttribute(estiloEClass, ESTILO__COR_SECUNDARIA);
    createEAttribute(estiloEClass, ESTILO__COR_TERCIARIA);

    listaCursosEClass = createEClass(LISTA_CURSOS);
    createEReference(listaCursosEClass, LISTA_CURSOS__CURSO);

    listaDisciplinasEClass = createEClass(LISTA_DISCIPLINAS);

    listaDepartamentosEClass = createEClass(LISTA_DEPARTAMENTOS);
    createEReference(listaDepartamentosEClass, LISTA_DEPARTAMENTOS__DEPARTAMENTO);

    listaPeriodosEClass = createEClass(LISTA_PERIODOS);
    createEReference(listaPeriodosEClass, LISTA_PERIODOS__PERIODO);

    cursoEClass = createEClass(CURSO);
    createEAttribute(cursoEClass, CURSO__NOME);
    createEReference(cursoEClass, CURSO__ORGANIZACAO_CURSO);

    departamentoEClass = createEClass(DEPARTAMENTO);
    createEAttribute(departamentoEClass, DEPARTAMENTO__NOME);
    createEReference(departamentoEClass, DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO);

    periodoEClass = createEClass(PERIODO);
    createEAttribute(periodoEClass, PERIODO__NOME);

    // Create enums
    fonteEEnum = createEEnum(FONTE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    listaCursosEClass.getESuperTypes().add(this.getSeparacaoDisciplinas());
    listaCursosEClass.getESuperTypes().add(this.getOrganizacaoDepartamento());
    listaDisciplinasEClass.getESuperTypes().add(this.getSeparacaoDisciplinas());
    listaDisciplinasEClass.getESuperTypes().add(this.getOrganizacaoCurso());
    listaDisciplinasEClass.getESuperTypes().add(this.getOrganizacaoDepartamento());
    listaDepartamentosEClass.getESuperTypes().add(this.getSeparacaoDisciplinas());
    listaPeriodosEClass.getESuperTypes().add(this.getSeparacaoDisciplinas());
    listaPeriodosEClass.getESuperTypes().add(this.getOrganizacaoCurso());
    listaPeriodosEClass.getESuperTypes().add(this.getOrganizacaoDepartamento());

    // Initialize classes and features; add operations and parameters
    initEClass(aplicativoEClass, Aplicativo.class, "Aplicativo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAplicativo_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAplicativo_Url(), ecorePackage.getEString(), "url", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAplicativo_SecaoEventos(), this.getSecaoEventos(), null, "secaoEventos", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAplicativo_SecaoMembros(), this.getSecaoMembros(), null, "secaoMembros", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAplicativo_SecaoDisciplinas(), this.getSecaoDisciplinas(), null, "secaoDisciplinas", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAplicativo_SecaoNoticias(), this.getSecaoNoticias(), null, "secaoNoticias", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAplicativo_Estilo(), this.getEstilo(), null, "estilo", null, 0, 1, Aplicativo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(separacaoDisciplinasEClass, SeparacaoDisciplinas.class, "SeparacaoDisciplinas", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(organizacaoCursoEClass, OrganizacaoCurso.class, "OrganizacaoCurso", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(organizacaoDepartamentoEClass, OrganizacaoDepartamento.class, "OrganizacaoDepartamento", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(secaoEventosEClass, SecaoEventos.class, "SecaoEventos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSecaoEventos_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, SecaoEventos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secaoMembrosEClass, SecaoMembros.class, "SecaoMembros", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSecaoMembros_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, SecaoMembros.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secaoDisciplinasEClass, SecaoDisciplinas.class, "SecaoDisciplinas", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSecaoDisciplinas_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, SecaoDisciplinas.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSecaoDisciplinas_SeparacaoDisciplinas(), this.getSeparacaoDisciplinas(), null, "separacaoDisciplinas", null, 0, 1, SecaoDisciplinas.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(secaoNoticiasEClass, SecaoNoticias.class, "SecaoNoticias", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSecaoNoticias_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, SecaoNoticias.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSecaoNoticias_Facebook(), ecorePackage.getEString(), "Facebook", null, 0, 1, SecaoNoticias.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(estiloEClass, Estilo.class, "Estilo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEstilo_Logo(), ecorePackage.getEString(), "logo", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEstilo_Fonte(), this.getFonte(), "fonte", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEstilo_CorPrimaria(), ecorePackage.getEString(), "corPrimaria", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEstilo_CorSecundaria(), ecorePackage.getEString(), "corSecundaria", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEstilo_CorTerciaria(), ecorePackage.getEString(), "corTerciaria", null, 0, 1, Estilo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(listaCursosEClass, ListaCursos.class, "ListaCursos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getListaCursos_Curso(), this.getCurso(), null, "curso", null, 0, -1, ListaCursos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(listaDisciplinasEClass, ListaDisciplinas.class, "ListaDisciplinas", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(listaDepartamentosEClass, ListaDepartamentos.class, "ListaDepartamentos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getListaDepartamentos_Departamento(), this.getDepartamento(), null, "departamento", null, 0, -1, ListaDepartamentos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(listaPeriodosEClass, ListaPeriodos.class, "ListaPeriodos", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getListaPeriodos_Periodo(), this.getPeriodo(), null, "periodo", null, 0, -1, ListaPeriodos.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(cursoEClass, Curso.class, "Curso", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCurso_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, Curso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCurso_OrganizacaoCurso(), this.getOrganizacaoCurso(), null, "organizacaoCurso", null, 0, 1, Curso.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(departamentoEClass, Departamento.class, "Departamento", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDepartamento_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, Departamento.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getDepartamento_OrganizacaoDepartamento(), this.getOrganizacaoDepartamento(), null, "organizacaoDepartamento", null, 0, 1, Departamento.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(periodoEClass, Periodo.class, "Periodo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeriodo_Nome(), ecorePackage.getEString(), "nome", null, 0, 1, Periodo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(fonteEEnum, Fonte.class, "Fonte");
    addEEnumLiteral(fonteEEnum, Fonte.NORMAL);
    addEEnumLiteral(fonteEEnum, Fonte.SANS);
    addEEnumLiteral(fonteEEnum, Fonte.SERIF);
    addEEnumLiteral(fonteEEnum, Fonte.MONOSPACE);

    // Create resource
    createResource(eNS_URI);
  }

} //AcedslPackageImpl
