/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.ace.acedsl.acedsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class AcedslFactoryImpl extends EFactoryImpl implements AcedslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static AcedslFactory init()
  {
    try
    {
      AcedslFactory theAcedslFactory = (AcedslFactory)EPackage.Registry.INSTANCE.getEFactory(AcedslPackage.eNS_URI);
      if (theAcedslFactory != null)
      {
        return theAcedslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new AcedslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AcedslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case AcedslPackage.APLICATIVO: return createAplicativo();
      case AcedslPackage.SEPARACAO_DISCIPLINAS: return createSeparacaoDisciplinas();
      case AcedslPackage.ORGANIZACAO_CURSO: return createOrganizacaoCurso();
      case AcedslPackage.ORGANIZACAO_DEPARTAMENTO: return createOrganizacaoDepartamento();
      case AcedslPackage.SECAO_EVENTOS: return createSecaoEventos();
      case AcedslPackage.SECAO_MEMBROS: return createSecaoMembros();
      case AcedslPackage.SECAO_DISCIPLINAS: return createSecaoDisciplinas();
      case AcedslPackage.SECAO_NOTICIAS: return createSecaoNoticias();
      case AcedslPackage.ESTILO: return createEstilo();
      case AcedslPackage.LISTA_CURSOS: return createListaCursos();
      case AcedslPackage.LISTA_DISCIPLINAS: return createListaDisciplinas();
      case AcedslPackage.LISTA_DEPARTAMENTOS: return createListaDepartamentos();
      case AcedslPackage.LISTA_PERIODOS: return createListaPeriodos();
      case AcedslPackage.CURSO: return createCurso();
      case AcedslPackage.DEPARTAMENTO: return createDepartamento();
      case AcedslPackage.PERIODO: return createPeriodo();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case AcedslPackage.FONTE:
        return createFonteFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case AcedslPackage.FONTE:
        return convertFonteToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Aplicativo createAplicativo()
  {
    AplicativoImpl aplicativo = new AplicativoImpl();
    return aplicativo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SeparacaoDisciplinas createSeparacaoDisciplinas()
  {
    SeparacaoDisciplinasImpl separacaoDisciplinas = new SeparacaoDisciplinasImpl();
    return separacaoDisciplinas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OrganizacaoCurso createOrganizacaoCurso()
  {
    OrganizacaoCursoImpl organizacaoCurso = new OrganizacaoCursoImpl();
    return organizacaoCurso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OrganizacaoDepartamento createOrganizacaoDepartamento()
  {
    OrganizacaoDepartamentoImpl organizacaoDepartamento = new OrganizacaoDepartamentoImpl();
    return organizacaoDepartamento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecaoEventos createSecaoEventos()
  {
    SecaoEventosImpl secaoEventos = new SecaoEventosImpl();
    return secaoEventos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecaoMembros createSecaoMembros()
  {
    SecaoMembrosImpl secaoMembros = new SecaoMembrosImpl();
    return secaoMembros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecaoDisciplinas createSecaoDisciplinas()
  {
    SecaoDisciplinasImpl secaoDisciplinas = new SecaoDisciplinasImpl();
    return secaoDisciplinas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecaoNoticias createSecaoNoticias()
  {
    SecaoNoticiasImpl secaoNoticias = new SecaoNoticiasImpl();
    return secaoNoticias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Estilo createEstilo()
  {
    EstiloImpl estilo = new EstiloImpl();
    return estilo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListaCursos createListaCursos()
  {
    ListaCursosImpl listaCursos = new ListaCursosImpl();
    return listaCursos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListaDisciplinas createListaDisciplinas()
  {
    ListaDisciplinasImpl listaDisciplinas = new ListaDisciplinasImpl();
    return listaDisciplinas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListaDepartamentos createListaDepartamentos()
  {
    ListaDepartamentosImpl listaDepartamentos = new ListaDepartamentosImpl();
    return listaDepartamentos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListaPeriodos createListaPeriodos()
  {
    ListaPeriodosImpl listaPeriodos = new ListaPeriodosImpl();
    return listaPeriodos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Curso createCurso()
  {
    CursoImpl curso = new CursoImpl();
    return curso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Departamento createDepartamento()
  {
    DepartamentoImpl departamento = new DepartamentoImpl();
    return departamento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Periodo createPeriodo()
  {
    PeriodoImpl periodo = new PeriodoImpl();
    return periodo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fonte createFonteFromString(EDataType eDataType, String initialValue)
  {
    Fonte result = Fonte.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertFonteToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AcedslPackage getAcedslPackage()
  {
    return (AcedslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static AcedslPackage getPackage()
  {
    return AcedslPackage.eINSTANCE;
  }

} //AcedslFactoryImpl
