/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.Curso;
import org.xtext.ace.acedsl.acedsl.OrganizacaoCurso;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Curso</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.CursoImpl#getNome <em>Nome</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.CursoImpl#getOrganizacaoCurso <em>Organizacao Curso</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CursoImpl extends MinimalEObjectImpl.Container implements Curso
{
  /**
   * The default value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected static final String NOME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected String nome = NOME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOrganizacaoCurso() <em>Organizacao Curso</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrganizacaoCurso()
   * @generated
   * @ordered
   */
  protected OrganizacaoCurso organizacaoCurso;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CursoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.CURSO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNome()
  {
    return nome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNome(String newNome)
  {
    String oldNome = nome;
    nome = newNome;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.CURSO__NOME, oldNome, nome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OrganizacaoCurso getOrganizacaoCurso()
  {
    return organizacaoCurso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOrganizacaoCurso(OrganizacaoCurso newOrganizacaoCurso, NotificationChain msgs)
  {
    OrganizacaoCurso oldOrganizacaoCurso = organizacaoCurso;
    organizacaoCurso = newOrganizacaoCurso;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AcedslPackage.CURSO__ORGANIZACAO_CURSO, oldOrganizacaoCurso, newOrganizacaoCurso);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOrganizacaoCurso(OrganizacaoCurso newOrganizacaoCurso)
  {
    if (newOrganizacaoCurso != organizacaoCurso)
    {
      NotificationChain msgs = null;
      if (organizacaoCurso != null)
        msgs = ((InternalEObject)organizacaoCurso).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.CURSO__ORGANIZACAO_CURSO, null, msgs);
      if (newOrganizacaoCurso != null)
        msgs = ((InternalEObject)newOrganizacaoCurso).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.CURSO__ORGANIZACAO_CURSO, null, msgs);
      msgs = basicSetOrganizacaoCurso(newOrganizacaoCurso, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.CURSO__ORGANIZACAO_CURSO, newOrganizacaoCurso, newOrganizacaoCurso));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AcedslPackage.CURSO__ORGANIZACAO_CURSO:
        return basicSetOrganizacaoCurso(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.CURSO__NOME:
        return getNome();
      case AcedslPackage.CURSO__ORGANIZACAO_CURSO:
        return getOrganizacaoCurso();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.CURSO__NOME:
        setNome((String)newValue);
        return;
      case AcedslPackage.CURSO__ORGANIZACAO_CURSO:
        setOrganizacaoCurso((OrganizacaoCurso)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.CURSO__NOME:
        setNome(NOME_EDEFAULT);
        return;
      case AcedslPackage.CURSO__ORGANIZACAO_CURSO:
        setOrganizacaoCurso((OrganizacaoCurso)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.CURSO__NOME:
        return NOME_EDEFAULT == null ? nome != null : !NOME_EDEFAULT.equals(nome);
      case AcedslPackage.CURSO__ORGANIZACAO_CURSO:
        return organizacaoCurso != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nome: ");
    result.append(nome);
    result.append(')');
    return result.toString();
  }

} //CursoImpl
