/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.Departamento;
import org.xtext.ace.acedsl.acedsl.OrganizacaoDepartamento;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Departamento</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl#getNome <em>Nome</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl#getOrganizacaoDepartamento <em>Organizacao Departamento</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DepartamentoImpl extends MinimalEObjectImpl.Container implements Departamento
{
  /**
   * The default value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected static final String NOME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected String nome = NOME_EDEFAULT;

  /**
   * The cached value of the '{@link #getOrganizacaoDepartamento() <em>Organizacao Departamento</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOrganizacaoDepartamento()
   * @generated
   * @ordered
   */
  protected OrganizacaoDepartamento organizacaoDepartamento;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DepartamentoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.DEPARTAMENTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNome()
  {
    return nome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNome(String newNome)
  {
    String oldNome = nome;
    nome = newNome;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.DEPARTAMENTO__NOME, oldNome, nome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OrganizacaoDepartamento getOrganizacaoDepartamento()
  {
    return organizacaoDepartamento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOrganizacaoDepartamento(OrganizacaoDepartamento newOrganizacaoDepartamento, NotificationChain msgs)
  {
    OrganizacaoDepartamento oldOrganizacaoDepartamento = organizacaoDepartamento;
    organizacaoDepartamento = newOrganizacaoDepartamento;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO, oldOrganizacaoDepartamento, newOrganizacaoDepartamento);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOrganizacaoDepartamento(OrganizacaoDepartamento newOrganizacaoDepartamento)
  {
    if (newOrganizacaoDepartamento != organizacaoDepartamento)
    {
      NotificationChain msgs = null;
      if (organizacaoDepartamento != null)
        msgs = ((InternalEObject)organizacaoDepartamento).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO, null, msgs);
      if (newOrganizacaoDepartamento != null)
        msgs = ((InternalEObject)newOrganizacaoDepartamento).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO, null, msgs);
      msgs = basicSetOrganizacaoDepartamento(newOrganizacaoDepartamento, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO, newOrganizacaoDepartamento, newOrganizacaoDepartamento));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO:
        return basicSetOrganizacaoDepartamento(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.DEPARTAMENTO__NOME:
        return getNome();
      case AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO:
        return getOrganizacaoDepartamento();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.DEPARTAMENTO__NOME:
        setNome((String)newValue);
        return;
      case AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO:
        setOrganizacaoDepartamento((OrganizacaoDepartamento)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.DEPARTAMENTO__NOME:
        setNome(NOME_EDEFAULT);
        return;
      case AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO:
        setOrganizacaoDepartamento((OrganizacaoDepartamento)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.DEPARTAMENTO__NOME:
        return NOME_EDEFAULT == null ? nome != null : !NOME_EDEFAULT.equals(nome);
      case AcedslPackage.DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO:
        return organizacaoDepartamento != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nome: ");
    result.append(nome);
    result.append(')');
    return result.toString();
  }

} //DepartamentoImpl
