/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.Estilo;
import org.xtext.ace.acedsl.acedsl.Fonte;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Estilo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl#getLogo <em>Logo</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl#getFonte <em>Fonte</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl#getCorPrimaria <em>Cor Primaria</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl#getCorSecundaria <em>Cor Secundaria</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl#getCorTerciaria <em>Cor Terciaria</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EstiloImpl extends MinimalEObjectImpl.Container implements Estilo
{
  /**
   * The default value of the '{@link #getLogo() <em>Logo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogo()
   * @generated
   * @ordered
   */
  protected static final String LOGO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLogo() <em>Logo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLogo()
   * @generated
   * @ordered
   */
  protected String logo = LOGO_EDEFAULT;

  /**
   * The default value of the '{@link #getFonte() <em>Fonte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFonte()
   * @generated
   * @ordered
   */
  protected static final Fonte FONTE_EDEFAULT = Fonte.NORMAL;

  /**
   * The cached value of the '{@link #getFonte() <em>Fonte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFonte()
   * @generated
   * @ordered
   */
  protected Fonte fonte = FONTE_EDEFAULT;

  /**
   * The default value of the '{@link #getCorPrimaria() <em>Cor Primaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorPrimaria()
   * @generated
   * @ordered
   */
  protected static final String COR_PRIMARIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCorPrimaria() <em>Cor Primaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorPrimaria()
   * @generated
   * @ordered
   */
  protected String corPrimaria = COR_PRIMARIA_EDEFAULT;

  /**
   * The default value of the '{@link #getCorSecundaria() <em>Cor Secundaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorSecundaria()
   * @generated
   * @ordered
   */
  protected static final String COR_SECUNDARIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCorSecundaria() <em>Cor Secundaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorSecundaria()
   * @generated
   * @ordered
   */
  protected String corSecundaria = COR_SECUNDARIA_EDEFAULT;

  /**
   * The default value of the '{@link #getCorTerciaria() <em>Cor Terciaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorTerciaria()
   * @generated
   * @ordered
   */
  protected static final String COR_TERCIARIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCorTerciaria() <em>Cor Terciaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorTerciaria()
   * @generated
   * @ordered
   */
  protected String corTerciaria = COR_TERCIARIA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EstiloImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.ESTILO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLogo()
  {
    return logo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLogo(String newLogo)
  {
    String oldLogo = logo;
    logo = newLogo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.ESTILO__LOGO, oldLogo, logo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fonte getFonte()
  {
    return fonte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFonte(Fonte newFonte)
  {
    Fonte oldFonte = fonte;
    fonte = newFonte == null ? FONTE_EDEFAULT : newFonte;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.ESTILO__FONTE, oldFonte, fonte));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCorPrimaria()
  {
    return corPrimaria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCorPrimaria(String newCorPrimaria)
  {
    String oldCorPrimaria = corPrimaria;
    corPrimaria = newCorPrimaria;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.ESTILO__COR_PRIMARIA, oldCorPrimaria, corPrimaria));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCorSecundaria()
  {
    return corSecundaria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCorSecundaria(String newCorSecundaria)
  {
    String oldCorSecundaria = corSecundaria;
    corSecundaria = newCorSecundaria;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.ESTILO__COR_SECUNDARIA, oldCorSecundaria, corSecundaria));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCorTerciaria()
  {
    return corTerciaria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCorTerciaria(String newCorTerciaria)
  {
    String oldCorTerciaria = corTerciaria;
    corTerciaria = newCorTerciaria;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.ESTILO__COR_TERCIARIA, oldCorTerciaria, corTerciaria));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.ESTILO__LOGO:
        return getLogo();
      case AcedslPackage.ESTILO__FONTE:
        return getFonte();
      case AcedslPackage.ESTILO__COR_PRIMARIA:
        return getCorPrimaria();
      case AcedslPackage.ESTILO__COR_SECUNDARIA:
        return getCorSecundaria();
      case AcedslPackage.ESTILO__COR_TERCIARIA:
        return getCorTerciaria();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.ESTILO__LOGO:
        setLogo((String)newValue);
        return;
      case AcedslPackage.ESTILO__FONTE:
        setFonte((Fonte)newValue);
        return;
      case AcedslPackage.ESTILO__COR_PRIMARIA:
        setCorPrimaria((String)newValue);
        return;
      case AcedslPackage.ESTILO__COR_SECUNDARIA:
        setCorSecundaria((String)newValue);
        return;
      case AcedslPackage.ESTILO__COR_TERCIARIA:
        setCorTerciaria((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.ESTILO__LOGO:
        setLogo(LOGO_EDEFAULT);
        return;
      case AcedslPackage.ESTILO__FONTE:
        setFonte(FONTE_EDEFAULT);
        return;
      case AcedslPackage.ESTILO__COR_PRIMARIA:
        setCorPrimaria(COR_PRIMARIA_EDEFAULT);
        return;
      case AcedslPackage.ESTILO__COR_SECUNDARIA:
        setCorSecundaria(COR_SECUNDARIA_EDEFAULT);
        return;
      case AcedslPackage.ESTILO__COR_TERCIARIA:
        setCorTerciaria(COR_TERCIARIA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.ESTILO__LOGO:
        return LOGO_EDEFAULT == null ? logo != null : !LOGO_EDEFAULT.equals(logo);
      case AcedslPackage.ESTILO__FONTE:
        return fonte != FONTE_EDEFAULT;
      case AcedslPackage.ESTILO__COR_PRIMARIA:
        return COR_PRIMARIA_EDEFAULT == null ? corPrimaria != null : !COR_PRIMARIA_EDEFAULT.equals(corPrimaria);
      case AcedslPackage.ESTILO__COR_SECUNDARIA:
        return COR_SECUNDARIA_EDEFAULT == null ? corSecundaria != null : !COR_SECUNDARIA_EDEFAULT.equals(corSecundaria);
      case AcedslPackage.ESTILO__COR_TERCIARIA:
        return COR_TERCIARIA_EDEFAULT == null ? corTerciaria != null : !COR_TERCIARIA_EDEFAULT.equals(corTerciaria);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (logo: ");
    result.append(logo);
    result.append(", fonte: ");
    result.append(fonte);
    result.append(", corPrimaria: ");
    result.append(corPrimaria);
    result.append(", corSecundaria: ");
    result.append(corSecundaria);
    result.append(", corTerciaria: ");
    result.append(corTerciaria);
    result.append(')');
    return result.toString();
  }

} //EstiloImpl
