/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.ListaDisciplinas;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lista Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ListaDisciplinasImpl extends SeparacaoDisciplinasImpl implements ListaDisciplinas
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListaDisciplinasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.LISTA_DISCIPLINAS;
  }

} //ListaDisciplinasImpl
