/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.ListaPeriodos;
import org.xtext.ace.acedsl.acedsl.Periodo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lista Periodos</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.ListaPeriodosImpl#getPeriodo <em>Periodo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ListaPeriodosImpl extends SeparacaoDisciplinasImpl implements ListaPeriodos
{
  /**
   * The cached value of the '{@link #getPeriodo() <em>Periodo</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeriodo()
   * @generated
   * @ordered
   */
  protected EList<Periodo> periodo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListaPeriodosImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.LISTA_PERIODOS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Periodo> getPeriodo()
  {
    if (periodo == null)
    {
      periodo = new EObjectContainmentEList<Periodo>(Periodo.class, this, AcedslPackage.LISTA_PERIODOS__PERIODO);
    }
    return periodo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_PERIODOS__PERIODO:
        return ((InternalEList<?>)getPeriodo()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_PERIODOS__PERIODO:
        return getPeriodo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_PERIODOS__PERIODO:
        getPeriodo().clear();
        getPeriodo().addAll((Collection<? extends Periodo>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_PERIODOS__PERIODO:
        getPeriodo().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_PERIODOS__PERIODO:
        return periodo != null && !periodo.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ListaPeriodosImpl
