/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.Departamento;
import org.xtext.ace.acedsl.acedsl.ListaDepartamentos;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lista Departamentos</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.ListaDepartamentosImpl#getDepartamento <em>Departamento</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ListaDepartamentosImpl extends SeparacaoDisciplinasImpl implements ListaDepartamentos
{
  /**
   * The cached value of the '{@link #getDepartamento() <em>Departamento</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepartamento()
   * @generated
   * @ordered
   */
  protected EList<Departamento> departamento;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ListaDepartamentosImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.LISTA_DEPARTAMENTOS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Departamento> getDepartamento()
  {
    if (departamento == null)
    {
      departamento = new EObjectContainmentEList<Departamento>(Departamento.class, this, AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO);
    }
    return departamento;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO:
        return ((InternalEList<?>)getDepartamento()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO:
        return getDepartamento();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO:
        getDepartamento().clear();
        getDepartamento().addAll((Collection<? extends Departamento>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO:
        getDepartamento().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.LISTA_DEPARTAMENTOS__DEPARTAMENTO:
        return departamento != null && !departamento.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ListaDepartamentosImpl
