/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.OrganizacaoDepartamento;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Organizacao Departamento</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OrganizacaoDepartamentoImpl extends MinimalEObjectImpl.Container implements OrganizacaoDepartamento
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OrganizacaoDepartamentoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.ORGANIZACAO_DEPARTAMENTO;
  }

} //OrganizacaoDepartamentoImpl
