/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.OrganizacaoCurso;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Organizacao Curso</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OrganizacaoCursoImpl extends MinimalEObjectImpl.Container implements OrganizacaoCurso
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OrganizacaoCursoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.ORGANIZACAO_CURSO;
  }

} //OrganizacaoCursoImpl
