/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.SecaoDisciplinas;
import org.xtext.ace.acedsl.acedsl.SeparacaoDisciplinas;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Secao Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl#getNome <em>Nome</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl#getSeparacaoDisciplinas <em>Separacao Disciplinas</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SecaoDisciplinasImpl extends MinimalEObjectImpl.Container implements SecaoDisciplinas
{
  /**
   * The default value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected static final String NOME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNome() <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNome()
   * @generated
   * @ordered
   */
  protected String nome = NOME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSeparacaoDisciplinas() <em>Separacao Disciplinas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeparacaoDisciplinas()
   * @generated
   * @ordered
   */
  protected SeparacaoDisciplinas separacaoDisciplinas;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SecaoDisciplinasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.SECAO_DISCIPLINAS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNome()
  {
    return nome;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNome(String newNome)
  {
    String oldNome = nome;
    nome = newNome;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.SECAO_DISCIPLINAS__NOME, oldNome, nome));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SeparacaoDisciplinas getSeparacaoDisciplinas()
  {
    return separacaoDisciplinas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSeparacaoDisciplinas(SeparacaoDisciplinas newSeparacaoDisciplinas, NotificationChain msgs)
  {
    SeparacaoDisciplinas oldSeparacaoDisciplinas = separacaoDisciplinas;
    separacaoDisciplinas = newSeparacaoDisciplinas;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS, oldSeparacaoDisciplinas, newSeparacaoDisciplinas);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSeparacaoDisciplinas(SeparacaoDisciplinas newSeparacaoDisciplinas)
  {
    if (newSeparacaoDisciplinas != separacaoDisciplinas)
    {
      NotificationChain msgs = null;
      if (separacaoDisciplinas != null)
        msgs = ((InternalEObject)separacaoDisciplinas).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS, null, msgs);
      if (newSeparacaoDisciplinas != null)
        msgs = ((InternalEObject)newSeparacaoDisciplinas).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS, null, msgs);
      msgs = basicSetSeparacaoDisciplinas(newSeparacaoDisciplinas, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS, newSeparacaoDisciplinas, newSeparacaoDisciplinas));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS:
        return basicSetSeparacaoDisciplinas(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AcedslPackage.SECAO_DISCIPLINAS__NOME:
        return getNome();
      case AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS:
        return getSeparacaoDisciplinas();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AcedslPackage.SECAO_DISCIPLINAS__NOME:
        setNome((String)newValue);
        return;
      case AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS:
        setSeparacaoDisciplinas((SeparacaoDisciplinas)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.SECAO_DISCIPLINAS__NOME:
        setNome(NOME_EDEFAULT);
        return;
      case AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS:
        setSeparacaoDisciplinas((SeparacaoDisciplinas)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AcedslPackage.SECAO_DISCIPLINAS__NOME:
        return NOME_EDEFAULT == null ? nome != null : !NOME_EDEFAULT.equals(nome);
      case AcedslPackage.SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS:
        return separacaoDisciplinas != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nome: ");
    result.append(nome);
    result.append(')');
    return result.toString();
  }

} //SecaoDisciplinasImpl
