/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.ace.acedsl.acedsl.AcedslPackage;
import org.xtext.ace.acedsl.acedsl.SeparacaoDisciplinas;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Separacao Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SeparacaoDisciplinasImpl extends MinimalEObjectImpl.Container implements SeparacaoDisciplinas
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SeparacaoDisciplinasImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AcedslPackage.Literals.SEPARACAO_DISCIPLINAS;
  }

} //SeparacaoDisciplinasImpl
