/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ace.acedsl.acedsl.AcedslFactory
 * @model kind="package"
 * @generated
 */
public interface AcedslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "acedsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/acedsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "acedsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AcedslPackage eINSTANCE = org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.AplicativoImpl <em>Aplicativo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.AplicativoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getAplicativo()
   * @generated
   */
  int APLICATIVO = 0;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__NOME = 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__URL = 1;

  /**
   * The feature id for the '<em><b>Secao Eventos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__SECAO_EVENTOS = 2;

  /**
   * The feature id for the '<em><b>Secao Membros</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__SECAO_MEMBROS = 3;

  /**
   * The feature id for the '<em><b>Secao Disciplinas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__SECAO_DISCIPLINAS = 4;

  /**
   * The feature id for the '<em><b>Secao Noticias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__SECAO_NOTICIAS = 5;

  /**
   * The feature id for the '<em><b>Estilo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO__ESTILO = 6;

  /**
   * The number of structural features of the '<em>Aplicativo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APLICATIVO_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.SeparacaoDisciplinasImpl <em>Separacao Disciplinas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.SeparacaoDisciplinasImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSeparacaoDisciplinas()
   * @generated
   */
  int SEPARACAO_DISCIPLINAS = 1;

  /**
   * The number of structural features of the '<em>Separacao Disciplinas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEPARACAO_DISCIPLINAS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.OrganizacaoCursoImpl <em>Organizacao Curso</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.OrganizacaoCursoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getOrganizacaoCurso()
   * @generated
   */
  int ORGANIZACAO_CURSO = 2;

  /**
   * The number of structural features of the '<em>Organizacao Curso</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORGANIZACAO_CURSO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.OrganizacaoDepartamentoImpl <em>Organizacao Departamento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.OrganizacaoDepartamentoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getOrganizacaoDepartamento()
   * @generated
   */
  int ORGANIZACAO_DEPARTAMENTO = 3;

  /**
   * The number of structural features of the '<em>Organizacao Departamento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORGANIZACAO_DEPARTAMENTO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoEventosImpl <em>Secao Eventos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.SecaoEventosImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoEventos()
   * @generated
   */
  int SECAO_EVENTOS = 4;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_EVENTOS__NOME = 0;

  /**
   * The number of structural features of the '<em>Secao Eventos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_EVENTOS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoMembrosImpl <em>Secao Membros</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.SecaoMembrosImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoMembros()
   * @generated
   */
  int SECAO_MEMBROS = 5;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_MEMBROS__NOME = 0;

  /**
   * The number of structural features of the '<em>Secao Membros</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_MEMBROS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl <em>Secao Disciplinas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoDisciplinas()
   * @generated
   */
  int SECAO_DISCIPLINAS = 6;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_DISCIPLINAS__NOME = 0;

  /**
   * The feature id for the '<em><b>Separacao Disciplinas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS = 1;

  /**
   * The number of structural features of the '<em>Secao Disciplinas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_DISCIPLINAS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoNoticiasImpl <em>Secao Noticias</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.SecaoNoticiasImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoNoticias()
   * @generated
   */
  int SECAO_NOTICIAS = 7;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_NOTICIAS__NOME = 0;

  /**
   * The feature id for the '<em><b>Facebook</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_NOTICIAS__FACEBOOK = 1;

  /**
   * The number of structural features of the '<em>Secao Noticias</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECAO_NOTICIAS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl <em>Estilo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.EstiloImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getEstilo()
   * @generated
   */
  int ESTILO = 8;

  /**
   * The feature id for the '<em><b>Logo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__LOGO = 0;

  /**
   * The feature id for the '<em><b>Fonte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__FONTE = 1;

  /**
   * The feature id for the '<em><b>Cor Primaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__COR_PRIMARIA = 2;

  /**
   * The feature id for the '<em><b>Cor Secundaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__COR_SECUNDARIA = 3;

  /**
   * The feature id for the '<em><b>Cor Terciaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO__COR_TERCIARIA = 4;

  /**
   * The number of structural features of the '<em>Estilo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTILO_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaCursosImpl <em>Lista Cursos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.ListaCursosImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaCursos()
   * @generated
   */
  int LISTA_CURSOS = 9;

  /**
   * The feature id for the '<em><b>Curso</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_CURSOS__CURSO = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lista Cursos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_CURSOS_FEATURE_COUNT = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaDisciplinasImpl <em>Lista Disciplinas</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.ListaDisciplinasImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaDisciplinas()
   * @generated
   */
  int LISTA_DISCIPLINAS = 10;

  /**
   * The number of structural features of the '<em>Lista Disciplinas</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_DISCIPLINAS_FEATURE_COUNT = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaDepartamentosImpl <em>Lista Departamentos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.ListaDepartamentosImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaDepartamentos()
   * @generated
   */
  int LISTA_DEPARTAMENTOS = 11;

  /**
   * The feature id for the '<em><b>Departamento</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_DEPARTAMENTOS__DEPARTAMENTO = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lista Departamentos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_DEPARTAMENTOS_FEATURE_COUNT = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaPeriodosImpl <em>Lista Periodos</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.ListaPeriodosImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaPeriodos()
   * @generated
   */
  int LISTA_PERIODOS = 12;

  /**
   * The feature id for the '<em><b>Periodo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_PERIODOS__PERIODO = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lista Periodos</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_PERIODOS_FEATURE_COUNT = SEPARACAO_DISCIPLINAS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.CursoImpl <em>Curso</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.CursoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getCurso()
   * @generated
   */
  int CURSO = 13;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CURSO__NOME = 0;

  /**
   * The feature id for the '<em><b>Organizacao Curso</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CURSO__ORGANIZACAO_CURSO = 1;

  /**
   * The number of structural features of the '<em>Curso</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CURSO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl <em>Departamento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getDepartamento()
   * @generated
   */
  int DEPARTAMENTO = 14;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPARTAMENTO__NOME = 0;

  /**
   * The feature id for the '<em><b>Organizacao Departamento</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO = 1;

  /**
   * The number of structural features of the '<em>Departamento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPARTAMENTO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.impl.PeriodoImpl <em>Periodo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.impl.PeriodoImpl
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getPeriodo()
   * @generated
   */
  int PERIODO = 15;

  /**
   * The feature id for the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODO__NOME = 0;

  /**
   * The number of structural features of the '<em>Periodo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ace.acedsl.acedsl.Fonte <em>Fonte</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ace.acedsl.acedsl.Fonte
   * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getFonte()
   * @generated
   */
  int FONTE = 16;


  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.Aplicativo <em>Aplicativo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aplicativo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo
   * @generated
   */
  EClass getAplicativo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getNome()
   * @see #getAplicativo()
   * @generated
   */
  EAttribute getAplicativo_Nome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getUrl()
   * @see #getAplicativo()
   * @generated
   */
  EAttribute getAplicativo_Url();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoEventos <em>Secao Eventos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secao Eventos</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoEventos()
   * @see #getAplicativo()
   * @generated
   */
  EReference getAplicativo_SecaoEventos();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoMembros <em>Secao Membros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secao Membros</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoMembros()
   * @see #getAplicativo()
   * @generated
   */
  EReference getAplicativo_SecaoMembros();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoDisciplinas <em>Secao Disciplinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secao Disciplinas</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoDisciplinas()
   * @see #getAplicativo()
   * @generated
   */
  EReference getAplicativo_SecaoDisciplinas();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoNoticias <em>Secao Noticias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Secao Noticias</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoNoticias()
   * @see #getAplicativo()
   * @generated
   */
  EReference getAplicativo_SecaoNoticias();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getEstilo <em>Estilo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Estilo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Aplicativo#getEstilo()
   * @see #getAplicativo()
   * @generated
   */
  EReference getAplicativo_Estilo();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.SeparacaoDisciplinas <em>Separacao Disciplinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Separacao Disciplinas</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SeparacaoDisciplinas
   * @generated
   */
  EClass getSeparacaoDisciplinas();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.OrganizacaoCurso <em>Organizacao Curso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Organizacao Curso</em>'.
   * @see org.xtext.ace.acedsl.acedsl.OrganizacaoCurso
   * @generated
   */
  EClass getOrganizacaoCurso();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.OrganizacaoDepartamento <em>Organizacao Departamento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Organizacao Departamento</em>'.
   * @see org.xtext.ace.acedsl.acedsl.OrganizacaoDepartamento
   * @generated
   */
  EClass getOrganizacaoDepartamento();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.SecaoEventos <em>Secao Eventos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Secao Eventos</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoEventos
   * @generated
   */
  EClass getSecaoEventos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.SecaoEventos#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoEventos#getNome()
   * @see #getSecaoEventos()
   * @generated
   */
  EAttribute getSecaoEventos_Nome();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.SecaoMembros <em>Secao Membros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Secao Membros</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoMembros
   * @generated
   */
  EClass getSecaoMembros();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.SecaoMembros#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoMembros#getNome()
   * @see #getSecaoMembros()
   * @generated
   */
  EAttribute getSecaoMembros_Nome();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas <em>Secao Disciplinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Secao Disciplinas</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoDisciplinas
   * @generated
   */
  EClass getSecaoDisciplinas();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getNome()
   * @see #getSecaoDisciplinas()
   * @generated
   */
  EAttribute getSecaoDisciplinas_Nome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getSeparacaoDisciplinas <em>Separacao Disciplinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Separacao Disciplinas</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getSeparacaoDisciplinas()
   * @see #getSecaoDisciplinas()
   * @generated
   */
  EReference getSecaoDisciplinas_SeparacaoDisciplinas();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.SecaoNoticias <em>Secao Noticias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Secao Noticias</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoNoticias
   * @generated
   */
  EClass getSecaoNoticias();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.SecaoNoticias#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoNoticias#getNome()
   * @see #getSecaoNoticias()
   * @generated
   */
  EAttribute getSecaoNoticias_Nome();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.SecaoNoticias#getFacebook <em>Facebook</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Facebook</em>'.
   * @see org.xtext.ace.acedsl.acedsl.SecaoNoticias#getFacebook()
   * @see #getSecaoNoticias()
   * @generated
   */
  EAttribute getSecaoNoticias_Facebook();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.Estilo <em>Estilo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Estilo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo
   * @generated
   */
  EClass getEstilo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Estilo#getLogo <em>Logo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo#getLogo()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_Logo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Estilo#getFonte <em>Fonte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fonte</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo#getFonte()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_Fonte();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorPrimaria <em>Cor Primaria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cor Primaria</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo#getCorPrimaria()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_CorPrimaria();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorSecundaria <em>Cor Secundaria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cor Secundaria</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo#getCorSecundaria()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_CorSecundaria();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorTerciaria <em>Cor Terciaria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cor Terciaria</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Estilo#getCorTerciaria()
   * @see #getEstilo()
   * @generated
   */
  EAttribute getEstilo_CorTerciaria();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.ListaCursos <em>Lista Cursos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista Cursos</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaCursos
   * @generated
   */
  EClass getListaCursos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ace.acedsl.acedsl.ListaCursos#getCurso <em>Curso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Curso</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaCursos#getCurso()
   * @see #getListaCursos()
   * @generated
   */
  EReference getListaCursos_Curso();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.ListaDisciplinas <em>Lista Disciplinas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista Disciplinas</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaDisciplinas
   * @generated
   */
  EClass getListaDisciplinas();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.ListaDepartamentos <em>Lista Departamentos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista Departamentos</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaDepartamentos
   * @generated
   */
  EClass getListaDepartamentos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ace.acedsl.acedsl.ListaDepartamentos#getDepartamento <em>Departamento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Departamento</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaDepartamentos#getDepartamento()
   * @see #getListaDepartamentos()
   * @generated
   */
  EReference getListaDepartamentos_Departamento();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.ListaPeriodos <em>Lista Periodos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lista Periodos</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaPeriodos
   * @generated
   */
  EClass getListaPeriodos();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ace.acedsl.acedsl.ListaPeriodos#getPeriodo <em>Periodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Periodo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.ListaPeriodos#getPeriodo()
   * @see #getListaPeriodos()
   * @generated
   */
  EReference getListaPeriodos_Periodo();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.Curso <em>Curso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Curso</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Curso
   * @generated
   */
  EClass getCurso();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Curso#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Curso#getNome()
   * @see #getCurso()
   * @generated
   */
  EAttribute getCurso_Nome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Curso#getOrganizacaoCurso <em>Organizacao Curso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Organizacao Curso</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Curso#getOrganizacaoCurso()
   * @see #getCurso()
   * @generated
   */
  EReference getCurso_OrganizacaoCurso();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.Departamento <em>Departamento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Departamento</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Departamento
   * @generated
   */
  EClass getDepartamento();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Departamento#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Departamento#getNome()
   * @see #getDepartamento()
   * @generated
   */
  EAttribute getDepartamento_Nome();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.ace.acedsl.acedsl.Departamento#getOrganizacaoDepartamento <em>Organizacao Departamento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Organizacao Departamento</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Departamento#getOrganizacaoDepartamento()
   * @see #getDepartamento()
   * @generated
   */
  EReference getDepartamento_OrganizacaoDepartamento();

  /**
   * Returns the meta object for class '{@link org.xtext.ace.acedsl.acedsl.Periodo <em>Periodo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Periodo</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Periodo
   * @generated
   */
  EClass getPeriodo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ace.acedsl.acedsl.Periodo#getNome <em>Nome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nome</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Periodo#getNome()
   * @see #getPeriodo()
   * @generated
   */
  EAttribute getPeriodo_Nome();

  /**
   * Returns the meta object for enum '{@link org.xtext.ace.acedsl.acedsl.Fonte <em>Fonte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Fonte</em>'.
   * @see org.xtext.ace.acedsl.acedsl.Fonte
   * @generated
   */
  EEnum getFonte();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AcedslFactory getAcedslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.AplicativoImpl <em>Aplicativo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.AplicativoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getAplicativo()
     * @generated
     */
    EClass APLICATIVO = eINSTANCE.getAplicativo();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APLICATIVO__NOME = eINSTANCE.getAplicativo_Nome();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APLICATIVO__URL = eINSTANCE.getAplicativo_Url();

    /**
     * The meta object literal for the '<em><b>Secao Eventos</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APLICATIVO__SECAO_EVENTOS = eINSTANCE.getAplicativo_SecaoEventos();

    /**
     * The meta object literal for the '<em><b>Secao Membros</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APLICATIVO__SECAO_MEMBROS = eINSTANCE.getAplicativo_SecaoMembros();

    /**
     * The meta object literal for the '<em><b>Secao Disciplinas</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APLICATIVO__SECAO_DISCIPLINAS = eINSTANCE.getAplicativo_SecaoDisciplinas();

    /**
     * The meta object literal for the '<em><b>Secao Noticias</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APLICATIVO__SECAO_NOTICIAS = eINSTANCE.getAplicativo_SecaoNoticias();

    /**
     * The meta object literal for the '<em><b>Estilo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APLICATIVO__ESTILO = eINSTANCE.getAplicativo_Estilo();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.SeparacaoDisciplinasImpl <em>Separacao Disciplinas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.SeparacaoDisciplinasImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSeparacaoDisciplinas()
     * @generated
     */
    EClass SEPARACAO_DISCIPLINAS = eINSTANCE.getSeparacaoDisciplinas();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.OrganizacaoCursoImpl <em>Organizacao Curso</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.OrganizacaoCursoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getOrganizacaoCurso()
     * @generated
     */
    EClass ORGANIZACAO_CURSO = eINSTANCE.getOrganizacaoCurso();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.OrganizacaoDepartamentoImpl <em>Organizacao Departamento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.OrganizacaoDepartamentoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getOrganizacaoDepartamento()
     * @generated
     */
    EClass ORGANIZACAO_DEPARTAMENTO = eINSTANCE.getOrganizacaoDepartamento();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoEventosImpl <em>Secao Eventos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.SecaoEventosImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoEventos()
     * @generated
     */
    EClass SECAO_EVENTOS = eINSTANCE.getSecaoEventos();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECAO_EVENTOS__NOME = eINSTANCE.getSecaoEventos_Nome();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoMembrosImpl <em>Secao Membros</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.SecaoMembrosImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoMembros()
     * @generated
     */
    EClass SECAO_MEMBROS = eINSTANCE.getSecaoMembros();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECAO_MEMBROS__NOME = eINSTANCE.getSecaoMembros_Nome();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl <em>Secao Disciplinas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.SecaoDisciplinasImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoDisciplinas()
     * @generated
     */
    EClass SECAO_DISCIPLINAS = eINSTANCE.getSecaoDisciplinas();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECAO_DISCIPLINAS__NOME = eINSTANCE.getSecaoDisciplinas_Nome();

    /**
     * The meta object literal for the '<em><b>Separacao Disciplinas</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECAO_DISCIPLINAS__SEPARACAO_DISCIPLINAS = eINSTANCE.getSecaoDisciplinas_SeparacaoDisciplinas();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.SecaoNoticiasImpl <em>Secao Noticias</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.SecaoNoticiasImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getSecaoNoticias()
     * @generated
     */
    EClass SECAO_NOTICIAS = eINSTANCE.getSecaoNoticias();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECAO_NOTICIAS__NOME = eINSTANCE.getSecaoNoticias_Nome();

    /**
     * The meta object literal for the '<em><b>Facebook</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECAO_NOTICIAS__FACEBOOK = eINSTANCE.getSecaoNoticias_Facebook();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.EstiloImpl <em>Estilo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.EstiloImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getEstilo()
     * @generated
     */
    EClass ESTILO = eINSTANCE.getEstilo();

    /**
     * The meta object literal for the '<em><b>Logo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__LOGO = eINSTANCE.getEstilo_Logo();

    /**
     * The meta object literal for the '<em><b>Fonte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__FONTE = eINSTANCE.getEstilo_Fonte();

    /**
     * The meta object literal for the '<em><b>Cor Primaria</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__COR_PRIMARIA = eINSTANCE.getEstilo_CorPrimaria();

    /**
     * The meta object literal for the '<em><b>Cor Secundaria</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__COR_SECUNDARIA = eINSTANCE.getEstilo_CorSecundaria();

    /**
     * The meta object literal for the '<em><b>Cor Terciaria</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESTILO__COR_TERCIARIA = eINSTANCE.getEstilo_CorTerciaria();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaCursosImpl <em>Lista Cursos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.ListaCursosImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaCursos()
     * @generated
     */
    EClass LISTA_CURSOS = eINSTANCE.getListaCursos();

    /**
     * The meta object literal for the '<em><b>Curso</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_CURSOS__CURSO = eINSTANCE.getListaCursos_Curso();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaDisciplinasImpl <em>Lista Disciplinas</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.ListaDisciplinasImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaDisciplinas()
     * @generated
     */
    EClass LISTA_DISCIPLINAS = eINSTANCE.getListaDisciplinas();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaDepartamentosImpl <em>Lista Departamentos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.ListaDepartamentosImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaDepartamentos()
     * @generated
     */
    EClass LISTA_DEPARTAMENTOS = eINSTANCE.getListaDepartamentos();

    /**
     * The meta object literal for the '<em><b>Departamento</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_DEPARTAMENTOS__DEPARTAMENTO = eINSTANCE.getListaDepartamentos_Departamento();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.ListaPeriodosImpl <em>Lista Periodos</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.ListaPeriodosImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getListaPeriodos()
     * @generated
     */
    EClass LISTA_PERIODOS = eINSTANCE.getListaPeriodos();

    /**
     * The meta object literal for the '<em><b>Periodo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_PERIODOS__PERIODO = eINSTANCE.getListaPeriodos_Periodo();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.CursoImpl <em>Curso</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.CursoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getCurso()
     * @generated
     */
    EClass CURSO = eINSTANCE.getCurso();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CURSO__NOME = eINSTANCE.getCurso_Nome();

    /**
     * The meta object literal for the '<em><b>Organizacao Curso</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CURSO__ORGANIZACAO_CURSO = eINSTANCE.getCurso_OrganizacaoCurso();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl <em>Departamento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.DepartamentoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getDepartamento()
     * @generated
     */
    EClass DEPARTAMENTO = eINSTANCE.getDepartamento();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPARTAMENTO__NOME = eINSTANCE.getDepartamento_Nome();

    /**
     * The meta object literal for the '<em><b>Organizacao Departamento</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPARTAMENTO__ORGANIZACAO_DEPARTAMENTO = eINSTANCE.getDepartamento_OrganizacaoDepartamento();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.impl.PeriodoImpl <em>Periodo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.impl.PeriodoImpl
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getPeriodo()
     * @generated
     */
    EClass PERIODO = eINSTANCE.getPeriodo();

    /**
     * The meta object literal for the '<em><b>Nome</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIODO__NOME = eINSTANCE.getPeriodo_Nome();

    /**
     * The meta object literal for the '{@link org.xtext.ace.acedsl.acedsl.Fonte <em>Fonte</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ace.acedsl.acedsl.Fonte
     * @see org.xtext.ace.acedsl.acedsl.impl.AcedslPackageImpl#getFonte()
     * @generated
     */
    EEnum FONTE = eINSTANCE.getFonte();

  }

} //AcedslPackage
