/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage
 * @generated
 */
public interface AcedslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AcedslFactory eINSTANCE = org.xtext.ace.acedsl.acedsl.impl.AcedslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Aplicativo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Aplicativo</em>'.
   * @generated
   */
  Aplicativo createAplicativo();

  /**
   * Returns a new object of class '<em>Separacao Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Separacao Disciplinas</em>'.
   * @generated
   */
  SeparacaoDisciplinas createSeparacaoDisciplinas();

  /**
   * Returns a new object of class '<em>Organizacao Curso</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Organizacao Curso</em>'.
   * @generated
   */
  OrganizacaoCurso createOrganizacaoCurso();

  /**
   * Returns a new object of class '<em>Organizacao Departamento</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Organizacao Departamento</em>'.
   * @generated
   */
  OrganizacaoDepartamento createOrganizacaoDepartamento();

  /**
   * Returns a new object of class '<em>Secao Eventos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Secao Eventos</em>'.
   * @generated
   */
  SecaoEventos createSecaoEventos();

  /**
   * Returns a new object of class '<em>Secao Membros</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Secao Membros</em>'.
   * @generated
   */
  SecaoMembros createSecaoMembros();

  /**
   * Returns a new object of class '<em>Secao Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Secao Disciplinas</em>'.
   * @generated
   */
  SecaoDisciplinas createSecaoDisciplinas();

  /**
   * Returns a new object of class '<em>Secao Noticias</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Secao Noticias</em>'.
   * @generated
   */
  SecaoNoticias createSecaoNoticias();

  /**
   * Returns a new object of class '<em>Estilo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Estilo</em>'.
   * @generated
   */
  Estilo createEstilo();

  /**
   * Returns a new object of class '<em>Lista Cursos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lista Cursos</em>'.
   * @generated
   */
  ListaCursos createListaCursos();

  /**
   * Returns a new object of class '<em>Lista Disciplinas</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lista Disciplinas</em>'.
   * @generated
   */
  ListaDisciplinas createListaDisciplinas();

  /**
   * Returns a new object of class '<em>Lista Departamentos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lista Departamentos</em>'.
   * @generated
   */
  ListaDepartamentos createListaDepartamentos();

  /**
   * Returns a new object of class '<em>Lista Periodos</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lista Periodos</em>'.
   * @generated
   */
  ListaPeriodos createListaPeriodos();

  /**
   * Returns a new object of class '<em>Curso</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Curso</em>'.
   * @generated
   */
  Curso createCurso();

  /**
   * Returns a new object of class '<em>Departamento</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Departamento</em>'.
   * @generated
   */
  Departamento createDepartamento();

  /**
   * Returns a new object of class '<em>Periodo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Periodo</em>'.
   * @generated
   */
  Periodo createPeriodo();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AcedslPackage getAcedslPackage();

} //AcedslFactory
