/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Aplicativo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getNome <em>Nome</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getUrl <em>Url</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoEventos <em>Secao Eventos</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoMembros <em>Secao Membros</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoDisciplinas <em>Secao Disciplinas</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoNoticias <em>Secao Noticias</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getEstilo <em>Estilo</em>}</li>
 * </ul>
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo()
 * @model
 * @generated
 */
public interface Aplicativo extends EObject
{
  /**
   * Returns the value of the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nome</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nome</em>' attribute.
   * @see #setNome(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_Nome()
   * @model
   * @generated
   */
  String getNome();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getNome <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nome</em>' attribute.
   * @see #getNome()
   * @generated
   */
  void setNome(String value);

  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Secao Eventos</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secao Eventos</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secao Eventos</em>' containment reference.
   * @see #setSecaoEventos(SecaoEventos)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_SecaoEventos()
   * @model containment="true"
   * @generated
   */
  SecaoEventos getSecaoEventos();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoEventos <em>Secao Eventos</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secao Eventos</em>' containment reference.
   * @see #getSecaoEventos()
   * @generated
   */
  void setSecaoEventos(SecaoEventos value);

  /**
   * Returns the value of the '<em><b>Secao Membros</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secao Membros</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secao Membros</em>' containment reference.
   * @see #setSecaoMembros(SecaoMembros)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_SecaoMembros()
   * @model containment="true"
   * @generated
   */
  SecaoMembros getSecaoMembros();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoMembros <em>Secao Membros</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secao Membros</em>' containment reference.
   * @see #getSecaoMembros()
   * @generated
   */
  void setSecaoMembros(SecaoMembros value);

  /**
   * Returns the value of the '<em><b>Secao Disciplinas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secao Disciplinas</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secao Disciplinas</em>' containment reference.
   * @see #setSecaoDisciplinas(SecaoDisciplinas)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_SecaoDisciplinas()
   * @model containment="true"
   * @generated
   */
  SecaoDisciplinas getSecaoDisciplinas();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoDisciplinas <em>Secao Disciplinas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secao Disciplinas</em>' containment reference.
   * @see #getSecaoDisciplinas()
   * @generated
   */
  void setSecaoDisciplinas(SecaoDisciplinas value);

  /**
   * Returns the value of the '<em><b>Secao Noticias</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secao Noticias</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secao Noticias</em>' containment reference.
   * @see #setSecaoNoticias(SecaoNoticias)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_SecaoNoticias()
   * @model containment="true"
   * @generated
   */
  SecaoNoticias getSecaoNoticias();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getSecaoNoticias <em>Secao Noticias</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secao Noticias</em>' containment reference.
   * @see #getSecaoNoticias()
   * @generated
   */
  void setSecaoNoticias(SecaoNoticias value);

  /**
   * Returns the value of the '<em><b>Estilo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Estilo</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Estilo</em>' containment reference.
   * @see #setEstilo(Estilo)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getAplicativo_Estilo()
   * @model containment="true"
   * @generated
   */
  Estilo getEstilo();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Aplicativo#getEstilo <em>Estilo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Estilo</em>' containment reference.
   * @see #getEstilo()
   * @generated
   */
  void setEstilo(Estilo value);

} // Aplicativo
