/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Estilo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Estilo#getLogo <em>Logo</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Estilo#getFonte <em>Fonte</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorPrimaria <em>Cor Primaria</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorSecundaria <em>Cor Secundaria</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorTerciaria <em>Cor Terciaria</em>}</li>
 * </ul>
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo()
 * @model
 * @generated
 */
public interface Estilo extends EObject
{
  /**
   * Returns the value of the '<em><b>Logo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Logo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logo</em>' attribute.
   * @see #setLogo(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo_Logo()
   * @model
   * @generated
   */
  String getLogo();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Estilo#getLogo <em>Logo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logo</em>' attribute.
   * @see #getLogo()
   * @generated
   */
  void setLogo(String value);

  /**
   * Returns the value of the '<em><b>Fonte</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.ace.acedsl.acedsl.Fonte}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fonte</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fonte</em>' attribute.
   * @see org.xtext.ace.acedsl.acedsl.Fonte
   * @see #setFonte(Fonte)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo_Fonte()
   * @model
   * @generated
   */
  Fonte getFonte();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Estilo#getFonte <em>Fonte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fonte</em>' attribute.
   * @see org.xtext.ace.acedsl.acedsl.Fonte
   * @see #getFonte()
   * @generated
   */
  void setFonte(Fonte value);

  /**
   * Returns the value of the '<em><b>Cor Primaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cor Primaria</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cor Primaria</em>' attribute.
   * @see #setCorPrimaria(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo_CorPrimaria()
   * @model
   * @generated
   */
  String getCorPrimaria();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorPrimaria <em>Cor Primaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cor Primaria</em>' attribute.
   * @see #getCorPrimaria()
   * @generated
   */
  void setCorPrimaria(String value);

  /**
   * Returns the value of the '<em><b>Cor Secundaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cor Secundaria</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cor Secundaria</em>' attribute.
   * @see #setCorSecundaria(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo_CorSecundaria()
   * @model
   * @generated
   */
  String getCorSecundaria();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorSecundaria <em>Cor Secundaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cor Secundaria</em>' attribute.
   * @see #getCorSecundaria()
   * @generated
   */
  void setCorSecundaria(String value);

  /**
   * Returns the value of the '<em><b>Cor Terciaria</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cor Terciaria</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cor Terciaria</em>' attribute.
   * @see #setCorTerciaria(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getEstilo_CorTerciaria()
   * @model
   * @generated
   */
  String getCorTerciaria();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.Estilo#getCorTerciaria <em>Cor Terciaria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cor Terciaria</em>' attribute.
   * @see #getCorTerciaria()
   * @generated
   */
  void setCorTerciaria(String value);

} // Estilo
