/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lista Departamentos</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.ListaDepartamentos#getDepartamento <em>Departamento</em>}</li>
 * </ul>
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getListaDepartamentos()
 * @model
 * @generated
 */
public interface ListaDepartamentos extends SeparacaoDisciplinas
{
  /**
   * Returns the value of the '<em><b>Departamento</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ace.acedsl.acedsl.Departamento}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Departamento</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Departamento</em>' containment reference list.
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getListaDepartamentos_Departamento()
   * @model containment="true"
   * @generated
   */
  EList<Departamento> getDepartamento();

} // ListaDepartamentos
