/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lista Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getListaDisciplinas()
 * @model
 * @generated
 */
public interface ListaDisciplinas extends SeparacaoDisciplinas, OrganizacaoCurso, OrganizacaoDepartamento
{
} // ListaDisciplinas
