/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Secao Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getNome <em>Nome</em>}</li>
 *   <li>{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getSeparacaoDisciplinas <em>Separacao Disciplinas</em>}</li>
 * </ul>
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getSecaoDisciplinas()
 * @model
 * @generated
 */
public interface SecaoDisciplinas extends EObject
{
  /**
   * Returns the value of the '<em><b>Nome</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nome</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nome</em>' attribute.
   * @see #setNome(String)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getSecaoDisciplinas_Nome()
   * @model
   * @generated
   */
  String getNome();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getNome <em>Nome</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nome</em>' attribute.
   * @see #getNome()
   * @generated
   */
  void setNome(String value);

  /**
   * Returns the value of the '<em><b>Separacao Disciplinas</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Separacao Disciplinas</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Separacao Disciplinas</em>' containment reference.
   * @see #setSeparacaoDisciplinas(SeparacaoDisciplinas)
   * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getSecaoDisciplinas_SeparacaoDisciplinas()
   * @model containment="true"
   * @generated
   */
  SeparacaoDisciplinas getSeparacaoDisciplinas();

  /**
   * Sets the value of the '{@link org.xtext.ace.acedsl.acedsl.SecaoDisciplinas#getSeparacaoDisciplinas <em>Separacao Disciplinas</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Separacao Disciplinas</em>' containment reference.
   * @see #getSeparacaoDisciplinas()
   * @generated
   */
  void setSeparacaoDisciplinas(SeparacaoDisciplinas value);

} // SecaoDisciplinas
