/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.acedsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Separacao Disciplinas</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.ace.acedsl.acedsl.AcedslPackage#getSeparacaoDisciplinas()
 * @model
 * @generated
 */
public interface SeparacaoDisciplinas extends EObject
{
} // SeparacaoDisciplinas
