/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.ace.acedsl.ui.internal.AcedslActivator;

public class AceDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AcedslActivator.getInstance().getInjector("org.xtext.ace.acedsl.AceDsl");
	}

}
