/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AceDslRuntimeModule extends AbstractAceDslRuntimeModule {
}
