/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AceDslStandaloneSetup extends AceDslStandaloneSetupGenerated {

	def static void doSetup() {
		new AceDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
