/*
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class AceDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class AplicativoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Aplicativo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAplicativoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final UnorderedGroup cUnorderedGroup_3 = (UnorderedGroup)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cUnorderedGroup_3.eContents().get(0);
		private final Keyword cUrlKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cUrlAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_3_0_1_0 = (RuleCall)cUrlAssignment_3_0_1.eContents().get(0);
		private final Assignment cSecaoEventosAssignment_3_1 = (Assignment)cUnorderedGroup_3.eContents().get(1);
		private final RuleCall cSecaoEventosSecaoEventosParserRuleCall_3_1_0 = (RuleCall)cSecaoEventosAssignment_3_1.eContents().get(0);
		private final Assignment cSecaoMembrosAssignment_3_2 = (Assignment)cUnorderedGroup_3.eContents().get(2);
		private final RuleCall cSecaoMembrosSecaoMembrosParserRuleCall_3_2_0 = (RuleCall)cSecaoMembrosAssignment_3_2.eContents().get(0);
		private final Assignment cSecaoDisciplinasAssignment_3_3 = (Assignment)cUnorderedGroup_3.eContents().get(3);
		private final RuleCall cSecaoDisciplinasSecaoDisciplinasParserRuleCall_3_3_0 = (RuleCall)cSecaoDisciplinasAssignment_3_3.eContents().get(0);
		private final Assignment cSecaoNoticiasAssignment_3_4 = (Assignment)cUnorderedGroup_3.eContents().get(4);
		private final RuleCall cSecaoNoticiasSecaoNoticiasParserRuleCall_3_4_0 = (RuleCall)cSecaoNoticiasAssignment_3_4.eContents().get(0);
		private final Assignment cEstiloAssignment_3_5 = (Assignment)cUnorderedGroup_3.eContents().get(5);
		private final RuleCall cEstiloEstiloParserRuleCall_3_5_0 = (RuleCall)cEstiloAssignment_3_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Aplicativo:
		//	'Aplicativo' nome=EString
		//	'{' ('url' url=EString & secaoEventos=SecaoEventos? & secaoMembros=SecaoMembros? & secaoDisciplinas=SecaoDisciplinas?
		//	& secaoNoticias=SecaoNoticias? & estilo=Estilo)
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Aplicativo' nome=EString '{' ('url' url=EString & secaoEventos=SecaoEventos? & secaoMembros=SecaoMembros? &
		//secaoDisciplinas=SecaoDisciplinas? & secaoNoticias=SecaoNoticias? & estilo=Estilo) '}'
		public Group getGroup() { return cGroup; }
		
		//'Aplicativo'
		public Keyword getAplicativoKeyword_0() { return cAplicativoKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('url' url=EString & secaoEventos=SecaoEventos? & secaoMembros=SecaoMembros? & secaoDisciplinas=SecaoDisciplinas? &
		//secaoNoticias=SecaoNoticias? & estilo=Estilo)
		public UnorderedGroup getUnorderedGroup_3() { return cUnorderedGroup_3; }
		
		//'url' url=EString
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'url'
		public Keyword getUrlKeyword_3_0_0() { return cUrlKeyword_3_0_0; }
		
		//url=EString
		public Assignment getUrlAssignment_3_0_1() { return cUrlAssignment_3_0_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0_1_0() { return cUrlEStringParserRuleCall_3_0_1_0; }
		
		//secaoEventos=SecaoEventos?
		public Assignment getSecaoEventosAssignment_3_1() { return cSecaoEventosAssignment_3_1; }
		
		//SecaoEventos
		public RuleCall getSecaoEventosSecaoEventosParserRuleCall_3_1_0() { return cSecaoEventosSecaoEventosParserRuleCall_3_1_0; }
		
		//secaoMembros=SecaoMembros?
		public Assignment getSecaoMembrosAssignment_3_2() { return cSecaoMembrosAssignment_3_2; }
		
		//SecaoMembros
		public RuleCall getSecaoMembrosSecaoMembrosParserRuleCall_3_2_0() { return cSecaoMembrosSecaoMembrosParserRuleCall_3_2_0; }
		
		//secaoDisciplinas=SecaoDisciplinas?
		public Assignment getSecaoDisciplinasAssignment_3_3() { return cSecaoDisciplinasAssignment_3_3; }
		
		//SecaoDisciplinas
		public RuleCall getSecaoDisciplinasSecaoDisciplinasParserRuleCall_3_3_0() { return cSecaoDisciplinasSecaoDisciplinasParserRuleCall_3_3_0; }
		
		//secaoNoticias=SecaoNoticias?
		public Assignment getSecaoNoticiasAssignment_3_4() { return cSecaoNoticiasAssignment_3_4; }
		
		//SecaoNoticias
		public RuleCall getSecaoNoticiasSecaoNoticiasParserRuleCall_3_4_0() { return cSecaoNoticiasSecaoNoticiasParserRuleCall_3_4_0; }
		
		//estilo=Estilo
		public Assignment getEstiloAssignment_3_5() { return cEstiloAssignment_3_5; }
		
		//Estilo
		public RuleCall getEstiloEstiloParserRuleCall_3_5_0() { return cEstiloEstiloParserRuleCall_3_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SeparacaoDisciplinasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.SeparacaoDisciplinas");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cListaCursosParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListaDisciplinasParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListaDepartamentosParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cListaPeriodosParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//SeparacaoDisciplinas:
		//	ListaCursos | ListaDisciplinas | ListaDepartamentos | ListaPeriodos;
		@Override public ParserRule getRule() { return rule; }
		
		//ListaCursos | ListaDisciplinas | ListaDepartamentos | ListaPeriodos
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ListaCursos
		public RuleCall getListaCursosParserRuleCall_0() { return cListaCursosParserRuleCall_0; }
		
		//ListaDisciplinas
		public RuleCall getListaDisciplinasParserRuleCall_1() { return cListaDisciplinasParserRuleCall_1; }
		
		//ListaDepartamentos
		public RuleCall getListaDepartamentosParserRuleCall_2() { return cListaDepartamentosParserRuleCall_2; }
		
		//ListaPeriodos
		public RuleCall getListaPeriodosParserRuleCall_3() { return cListaPeriodosParserRuleCall_3; }
	}
	public class OrganizacaoCursoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.OrganizacaoCurso");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cListaDisciplinasParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListaPeriodosParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//OrganizacaoCurso:
		//	ListaDisciplinas | ListaPeriodos;
		@Override public ParserRule getRule() { return rule; }
		
		//ListaDisciplinas | ListaPeriodos
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ListaDisciplinas
		public RuleCall getListaDisciplinasParserRuleCall_0() { return cListaDisciplinasParserRuleCall_0; }
		
		//ListaPeriodos
		public RuleCall getListaPeriodosParserRuleCall_1() { return cListaPeriodosParserRuleCall_1; }
	}
	public class OrganizacaoDepartamentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.OrganizacaoDepartamento");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cListaCursosParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cListaDisciplinasParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListaPeriodosParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//OrganizacaoDepartamento:
		//	ListaCursos | ListaDisciplinas | ListaPeriodos;
		@Override public ParserRule getRule() { return rule; }
		
		//ListaCursos | ListaDisciplinas | ListaPeriodos
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ListaCursos
		public RuleCall getListaCursosParserRuleCall_0() { return cListaCursosParserRuleCall_0; }
		
		//ListaDisciplinas
		public RuleCall getListaDisciplinasParserRuleCall_1() { return cListaDisciplinasParserRuleCall_1; }
		
		//ListaPeriodos
		public RuleCall getListaPeriodosParserRuleCall_2() { return cListaPeriodosParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SecaoEventosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.SecaoEventos");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSecaoEventosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		
		//SecaoEventos:
		//	'secao eventos' nome=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'secao eventos' nome=EString
		public Group getGroup() { return cGroup; }
		
		//'secao eventos'
		public Keyword getSecaoEventosKeyword_0() { return cSecaoEventosKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
	}
	public class SecaoMembrosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.SecaoMembros");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSecaoMembrosKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		
		//SecaoMembros:
		//	'secao membros' nome=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'secao membros' nome=EString
		public Group getGroup() { return cGroup; }
		
		//'secao membros'
		public Keyword getSecaoMembrosKeyword_0() { return cSecaoMembrosKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
	}
	public class SecaoDisciplinasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.SecaoDisciplinas");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSecaoDisciplinasKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSeparacaoDisciplinasAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSeparacaoDisciplinasSeparacaoDisciplinasParserRuleCall_3_0 = (RuleCall)cSeparacaoDisciplinasAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SecaoDisciplinas:
		//	'secao disciplinas' nome=EString
		//	'{'
		//	separacaoDisciplinas=SeparacaoDisciplinas
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'secao disciplinas' nome=EString '{' separacaoDisciplinas=SeparacaoDisciplinas '}'
		public Group getGroup() { return cGroup; }
		
		//'secao disciplinas'
		public Keyword getSecaoDisciplinasKeyword_0() { return cSecaoDisciplinasKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//separacaoDisciplinas=SeparacaoDisciplinas
		public Assignment getSeparacaoDisciplinasAssignment_3() { return cSeparacaoDisciplinasAssignment_3; }
		
		//SeparacaoDisciplinas
		public RuleCall getSeparacaoDisciplinasSeparacaoDisciplinasParserRuleCall_3_0() { return cSeparacaoDisciplinasSeparacaoDisciplinasParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SecaoNoticiasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.SecaoNoticias");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSecaoNoticiasKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cFacebookKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cFacebookAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cFacebookEStringParserRuleCall_2_1_1_0 = (RuleCall)cFacebookAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//SecaoNoticias:
		//	'secao noticias' nome=EString ('{' ('Facebook' Facebook=EString)?
		//	'}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'secao noticias' nome=EString ('{' ('Facebook' Facebook=EString)? '}')?
		public Group getGroup() { return cGroup; }
		
		//'secao noticias'
		public Keyword getSecaoNoticiasKeyword_0() { return cSecaoNoticiasKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
		
		//('{' ('Facebook' Facebook=EString)? '}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('Facebook' Facebook=EString)?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'Facebook'
		public Keyword getFacebookKeyword_2_1_0() { return cFacebookKeyword_2_1_0; }
		
		//Facebook=EString
		public Assignment getFacebookAssignment_2_1_1() { return cFacebookAssignment_2_1_1; }
		
		//EString
		public RuleCall getFacebookEStringParserRuleCall_2_1_1_0() { return cFacebookEStringParserRuleCall_2_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }
	}
	public class EstiloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Estilo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEstiloKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cLogoKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cLogoAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cLogoEStringParserRuleCall_2_0_1_0 = (RuleCall)cLogoAssignment_2_0_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cFonteKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cFonteAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cFonteFonteEnumRuleCall_2_1_1_0 = (RuleCall)cFonteAssignment_2_1_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cCorPrimariaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cCorPrimariaAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cCorPrimariaEStringParserRuleCall_2_2_1_0 = (RuleCall)cCorPrimariaAssignment_2_2_1.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cUnorderedGroup_2.eContents().get(3);
		private final Keyword cCorSecundariaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cCorSecundariaAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cCorSecundariaEStringParserRuleCall_2_3_1_0 = (RuleCall)cCorSecundariaAssignment_2_3_1.eContents().get(0);
		private final Group cGroup_2_4 = (Group)cUnorderedGroup_2.eContents().get(4);
		private final Keyword cCorTerciariaKeyword_2_4_0 = (Keyword)cGroup_2_4.eContents().get(0);
		private final Assignment cCorTerciariaAssignment_2_4_1 = (Assignment)cGroup_2_4.eContents().get(1);
		private final RuleCall cCorTerciariaEStringParserRuleCall_2_4_1_0 = (RuleCall)cCorTerciariaAssignment_2_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Estilo:
		//	'estilo'
		//	'{' ('logo' logo=EString & ('fonte' fonte=Fonte)? &
		//	'corPrimaria' corPrimaria=EString &
		//	'corSecundaria' corSecundaria=EString &
		//	'corTerciaria' corTerciaria=EString)
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'estilo' '{' ('logo' logo=EString & ('fonte' fonte=Fonte)? & 'corPrimaria' corPrimaria=EString & 'corSecundaria'
		//corSecundaria=EString & 'corTerciaria' corTerciaria=EString) '}'
		public Group getGroup() { return cGroup; }
		
		//'estilo'
		public Keyword getEstiloKeyword_0() { return cEstiloKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('logo' logo=EString & ('fonte' fonte=Fonte)? & 'corPrimaria' corPrimaria=EString & 'corSecundaria'
		//corSecundaria=EString & 'corTerciaria' corTerciaria=EString)
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//'logo' logo=EString
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'logo'
		public Keyword getLogoKeyword_2_0_0() { return cLogoKeyword_2_0_0; }
		
		//logo=EString
		public Assignment getLogoAssignment_2_0_1() { return cLogoAssignment_2_0_1; }
		
		//EString
		public RuleCall getLogoEStringParserRuleCall_2_0_1_0() { return cLogoEStringParserRuleCall_2_0_1_0; }
		
		//('fonte' fonte=Fonte)?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'fonte'
		public Keyword getFonteKeyword_2_1_0() { return cFonteKeyword_2_1_0; }
		
		//fonte=Fonte
		public Assignment getFonteAssignment_2_1_1() { return cFonteAssignment_2_1_1; }
		
		//Fonte
		public RuleCall getFonteFonteEnumRuleCall_2_1_1_0() { return cFonteFonteEnumRuleCall_2_1_1_0; }
		
		//'corPrimaria' corPrimaria=EString
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'corPrimaria'
		public Keyword getCorPrimariaKeyword_2_2_0() { return cCorPrimariaKeyword_2_2_0; }
		
		//corPrimaria=EString
		public Assignment getCorPrimariaAssignment_2_2_1() { return cCorPrimariaAssignment_2_2_1; }
		
		//EString
		public RuleCall getCorPrimariaEStringParserRuleCall_2_2_1_0() { return cCorPrimariaEStringParserRuleCall_2_2_1_0; }
		
		//'corSecundaria' corSecundaria=EString
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'corSecundaria'
		public Keyword getCorSecundariaKeyword_2_3_0() { return cCorSecundariaKeyword_2_3_0; }
		
		//corSecundaria=EString
		public Assignment getCorSecundariaAssignment_2_3_1() { return cCorSecundariaAssignment_2_3_1; }
		
		//EString
		public RuleCall getCorSecundariaEStringParserRuleCall_2_3_1_0() { return cCorSecundariaEStringParserRuleCall_2_3_1_0; }
		
		//'corTerciaria' corTerciaria=EString
		public Group getGroup_2_4() { return cGroup_2_4; }
		
		//'corTerciaria'
		public Keyword getCorTerciariaKeyword_2_4_0() { return cCorTerciariaKeyword_2_4_0; }
		
		//corTerciaria=EString
		public Assignment getCorTerciariaAssignment_2_4_1() { return cCorTerciariaAssignment_2_4_1; }
		
		//EString
		public RuleCall getCorTerciariaEStringParserRuleCall_2_4_1_0() { return cCorTerciariaEStringParserRuleCall_2_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ListaCursosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.ListaCursos");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCursoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCursoCursoParserRuleCall_0_0 = (RuleCall)cCursoAssignment_0.eContents().get(0);
		private final Assignment cCursoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCursoCursoParserRuleCall_1_0 = (RuleCall)cCursoAssignment_1.eContents().get(0);
		
		//ListaCursos:
		//	curso+=Curso
		//	curso+=Curso*;
		@Override public ParserRule getRule() { return rule; }
		
		//curso+=Curso curso+=Curso*
		public Group getGroup() { return cGroup; }
		
		//curso+=Curso
		public Assignment getCursoAssignment_0() { return cCursoAssignment_0; }
		
		//Curso
		public RuleCall getCursoCursoParserRuleCall_0_0() { return cCursoCursoParserRuleCall_0_0; }
		
		//curso+=Curso*
		public Assignment getCursoAssignment_1() { return cCursoAssignment_1; }
		
		//Curso
		public RuleCall getCursoCursoParserRuleCall_1_0() { return cCursoCursoParserRuleCall_1_0; }
	}
	public class ListaDisciplinasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.ListaDisciplinas");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cListaDisciplinasAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDisciplinasKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//ListaDisciplinas:
		//	{ListaDisciplinas}
		//	'disciplinas';
		@Override public ParserRule getRule() { return rule; }
		
		//{ListaDisciplinas} 'disciplinas'
		public Group getGroup() { return cGroup; }
		
		//{ListaDisciplinas}
		public Action getListaDisciplinasAction_0() { return cListaDisciplinasAction_0; }
		
		//'disciplinas'
		public Keyword getDisciplinasKeyword_1() { return cDisciplinasKeyword_1; }
	}
	public class ListaDepartamentosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.ListaDepartamentos");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDepartamentoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDepartamentoDepartamentoParserRuleCall_0_0 = (RuleCall)cDepartamentoAssignment_0.eContents().get(0);
		private final Assignment cDepartamentoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDepartamentoDepartamentoParserRuleCall_1_0 = (RuleCall)cDepartamentoAssignment_1.eContents().get(0);
		
		//ListaDepartamentos:
		//	departamento+=Departamento
		//	departamento+=Departamento*;
		@Override public ParserRule getRule() { return rule; }
		
		//departamento+=Departamento departamento+=Departamento*
		public Group getGroup() { return cGroup; }
		
		//departamento+=Departamento
		public Assignment getDepartamentoAssignment_0() { return cDepartamentoAssignment_0; }
		
		//Departamento
		public RuleCall getDepartamentoDepartamentoParserRuleCall_0_0() { return cDepartamentoDepartamentoParserRuleCall_0_0; }
		
		//departamento+=Departamento*
		public Assignment getDepartamentoAssignment_1() { return cDepartamentoAssignment_1; }
		
		//Departamento
		public RuleCall getDepartamentoDepartamentoParserRuleCall_1_0() { return cDepartamentoDepartamentoParserRuleCall_1_0; }
	}
	public class ListaPeriodosElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.ListaPeriodos");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPeriodoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPeriodoPeriodoParserRuleCall_0_0 = (RuleCall)cPeriodoAssignment_0.eContents().get(0);
		private final Assignment cPeriodoAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPeriodoPeriodoParserRuleCall_1_0 = (RuleCall)cPeriodoAssignment_1.eContents().get(0);
		
		//ListaPeriodos:
		//	periodo+=Periodo
		//	periodo+=Periodo*;
		@Override public ParserRule getRule() { return rule; }
		
		//periodo+=Periodo periodo+=Periodo*
		public Group getGroup() { return cGroup; }
		
		//periodo+=Periodo
		public Assignment getPeriodoAssignment_0() { return cPeriodoAssignment_0; }
		
		//Periodo
		public RuleCall getPeriodoPeriodoParserRuleCall_0_0() { return cPeriodoPeriodoParserRuleCall_0_0; }
		
		//periodo+=Periodo*
		public Assignment getPeriodoAssignment_1() { return cPeriodoAssignment_1; }
		
		//Periodo
		public RuleCall getPeriodoPeriodoParserRuleCall_1_0() { return cPeriodoPeriodoParserRuleCall_1_0; }
	}
	public class CursoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Curso");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCursoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOrganizacaoCursoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOrganizacaoCursoOrganizacaoCursoParserRuleCall_3_0 = (RuleCall)cOrganizacaoCursoAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Curso:
		//	'curso' nome=EString
		//	'{'
		//	organizacaoCurso=OrganizacaoCurso
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'curso' nome=EString '{' organizacaoCurso=OrganizacaoCurso '}'
		public Group getGroup() { return cGroup; }
		
		//'curso'
		public Keyword getCursoKeyword_0() { return cCursoKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//organizacaoCurso=OrganizacaoCurso
		public Assignment getOrganizacaoCursoAssignment_3() { return cOrganizacaoCursoAssignment_3; }
		
		//OrganizacaoCurso
		public RuleCall getOrganizacaoCursoOrganizacaoCursoParserRuleCall_3_0() { return cOrganizacaoCursoOrganizacaoCursoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class DepartamentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Departamento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDepartamentoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOrganizacaoDepartamentoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOrganizacaoDepartamentoOrganizacaoDepartamentoParserRuleCall_3_0 = (RuleCall)cOrganizacaoDepartamentoAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Departamento:
		//	'departamento' nome=EString
		//	'{'
		//	organizacaoDepartamento=OrganizacaoDepartamento
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'departamento' nome=EString '{' organizacaoDepartamento=OrganizacaoDepartamento '}'
		public Group getGroup() { return cGroup; }
		
		//'departamento'
		public Keyword getDepartamentoKeyword_0() { return cDepartamentoKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//organizacaoDepartamento=OrganizacaoDepartamento
		public Assignment getOrganizacaoDepartamentoAssignment_3() { return cOrganizacaoDepartamentoAssignment_3; }
		
		//OrganizacaoDepartamento
		public RuleCall getOrganizacaoDepartamentoOrganizacaoDepartamentoParserRuleCall_3_0() { return cOrganizacaoDepartamentoOrganizacaoDepartamentoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PeriodoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Periodo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPeriodoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNomeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNomeEStringParserRuleCall_1_0 = (RuleCall)cNomeAssignment_1.eContents().get(0);
		
		//Periodo:
		//	'periodo' nome=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'periodo' nome=EString
		public Group getGroup() { return cGroup; }
		
		//'periodo'
		public Keyword getPeriodoKeyword_0() { return cPeriodoKeyword_0; }
		
		//nome=EString
		public Assignment getNomeAssignment_1() { return cNomeAssignment_1; }
		
		//EString
		public RuleCall getNomeEStringParserRuleCall_1_0() { return cNomeEStringParserRuleCall_1_0; }
	}
	
	public class FonteElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ace.acedsl.AceDsl.Fonte");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNormalEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNormalNormalKeyword_0_0 = (Keyword)cNormalEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSansEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSansSansKeyword_1_0 = (Keyword)cSansEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSerifEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSerifSerifKeyword_2_0 = (Keyword)cSerifEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMonospaceEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMonospaceMonospaceKeyword_3_0 = (Keyword)cMonospaceEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Fonte:
		//	Normal | Sans | Serif | Monospace;
		public EnumRule getRule() { return rule; }
		
		//Normal | Sans | Serif | Monospace
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Normal
		public EnumLiteralDeclaration getNormalEnumLiteralDeclaration_0() { return cNormalEnumLiteralDeclaration_0; }
		
		//'Normal'
		public Keyword getNormalNormalKeyword_0_0() { return cNormalNormalKeyword_0_0; }
		
		//Sans
		public EnumLiteralDeclaration getSansEnumLiteralDeclaration_1() { return cSansEnumLiteralDeclaration_1; }
		
		//'Sans'
		public Keyword getSansSansKeyword_1_0() { return cSansSansKeyword_1_0; }
		
		//Serif
		public EnumLiteralDeclaration getSerifEnumLiteralDeclaration_2() { return cSerifEnumLiteralDeclaration_2; }
		
		//'Serif'
		public Keyword getSerifSerifKeyword_2_0() { return cSerifSerifKeyword_2_0; }
		
		//Monospace
		public EnumLiteralDeclaration getMonospaceEnumLiteralDeclaration_3() { return cMonospaceEnumLiteralDeclaration_3; }
		
		//'Monospace'
		public Keyword getMonospaceMonospaceKeyword_3_0() { return cMonospaceMonospaceKeyword_3_0; }
	}
	
	private final AplicativoElements pAplicativo;
	private final SeparacaoDisciplinasElements pSeparacaoDisciplinas;
	private final OrganizacaoCursoElements pOrganizacaoCurso;
	private final OrganizacaoDepartamentoElements pOrganizacaoDepartamento;
	private final EStringElements pEString;
	private final SecaoEventosElements pSecaoEventos;
	private final SecaoMembrosElements pSecaoMembros;
	private final SecaoDisciplinasElements pSecaoDisciplinas;
	private final SecaoNoticiasElements pSecaoNoticias;
	private final EstiloElements pEstilo;
	private final ListaCursosElements pListaCursos;
	private final ListaDisciplinasElements pListaDisciplinas;
	private final ListaDepartamentosElements pListaDepartamentos;
	private final ListaPeriodosElements pListaPeriodos;
	private final CursoElements pCurso;
	private final DepartamentoElements pDepartamento;
	private final PeriodoElements pPeriodo;
	private final FonteElements eFonte;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AceDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAplicativo = new AplicativoElements();
		this.pSeparacaoDisciplinas = new SeparacaoDisciplinasElements();
		this.pOrganizacaoCurso = new OrganizacaoCursoElements();
		this.pOrganizacaoDepartamento = new OrganizacaoDepartamentoElements();
		this.pEString = new EStringElements();
		this.pSecaoEventos = new SecaoEventosElements();
		this.pSecaoMembros = new SecaoMembrosElements();
		this.pSecaoDisciplinas = new SecaoDisciplinasElements();
		this.pSecaoNoticias = new SecaoNoticiasElements();
		this.pEstilo = new EstiloElements();
		this.pListaCursos = new ListaCursosElements();
		this.pListaDisciplinas = new ListaDisciplinasElements();
		this.pListaDepartamentos = new ListaDepartamentosElements();
		this.pListaPeriodos = new ListaPeriodosElements();
		this.pCurso = new CursoElements();
		this.pDepartamento = new DepartamentoElements();
		this.pPeriodo = new PeriodoElements();
		this.eFonte = new FonteElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.ace.acedsl.AceDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Aplicativo:
	//	'Aplicativo' nome=EString
	//	'{' ('url' url=EString & secaoEventos=SecaoEventos? & secaoMembros=SecaoMembros? & secaoDisciplinas=SecaoDisciplinas?
	//	& secaoNoticias=SecaoNoticias? & estilo=Estilo)
	//	'}';
	public AplicativoElements getAplicativoAccess() {
		return pAplicativo;
	}
	
	public ParserRule getAplicativoRule() {
		return getAplicativoAccess().getRule();
	}
	
	//SeparacaoDisciplinas:
	//	ListaCursos | ListaDisciplinas | ListaDepartamentos | ListaPeriodos;
	public SeparacaoDisciplinasElements getSeparacaoDisciplinasAccess() {
		return pSeparacaoDisciplinas;
	}
	
	public ParserRule getSeparacaoDisciplinasRule() {
		return getSeparacaoDisciplinasAccess().getRule();
	}
	
	//OrganizacaoCurso:
	//	ListaDisciplinas | ListaPeriodos;
	public OrganizacaoCursoElements getOrganizacaoCursoAccess() {
		return pOrganizacaoCurso;
	}
	
	public ParserRule getOrganizacaoCursoRule() {
		return getOrganizacaoCursoAccess().getRule();
	}
	
	//OrganizacaoDepartamento:
	//	ListaCursos | ListaDisciplinas | ListaPeriodos;
	public OrganizacaoDepartamentoElements getOrganizacaoDepartamentoAccess() {
		return pOrganizacaoDepartamento;
	}
	
	public ParserRule getOrganizacaoDepartamentoRule() {
		return getOrganizacaoDepartamentoAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//SecaoEventos:
	//	'secao eventos' nome=EString;
	public SecaoEventosElements getSecaoEventosAccess() {
		return pSecaoEventos;
	}
	
	public ParserRule getSecaoEventosRule() {
		return getSecaoEventosAccess().getRule();
	}
	
	//SecaoMembros:
	//	'secao membros' nome=EString;
	public SecaoMembrosElements getSecaoMembrosAccess() {
		return pSecaoMembros;
	}
	
	public ParserRule getSecaoMembrosRule() {
		return getSecaoMembrosAccess().getRule();
	}
	
	//SecaoDisciplinas:
	//	'secao disciplinas' nome=EString
	//	'{'
	//	separacaoDisciplinas=SeparacaoDisciplinas
	//	'}';
	public SecaoDisciplinasElements getSecaoDisciplinasAccess() {
		return pSecaoDisciplinas;
	}
	
	public ParserRule getSecaoDisciplinasRule() {
		return getSecaoDisciplinasAccess().getRule();
	}
	
	//SecaoNoticias:
	//	'secao noticias' nome=EString ('{' ('Facebook' Facebook=EString)?
	//	'}')?;
	public SecaoNoticiasElements getSecaoNoticiasAccess() {
		return pSecaoNoticias;
	}
	
	public ParserRule getSecaoNoticiasRule() {
		return getSecaoNoticiasAccess().getRule();
	}
	
	//Estilo:
	//	'estilo'
	//	'{' ('logo' logo=EString & ('fonte' fonte=Fonte)? &
	//	'corPrimaria' corPrimaria=EString &
	//	'corSecundaria' corSecundaria=EString &
	//	'corTerciaria' corTerciaria=EString)
	//	'}';
	public EstiloElements getEstiloAccess() {
		return pEstilo;
	}
	
	public ParserRule getEstiloRule() {
		return getEstiloAccess().getRule();
	}
	
	//ListaCursos:
	//	curso+=Curso
	//	curso+=Curso*;
	public ListaCursosElements getListaCursosAccess() {
		return pListaCursos;
	}
	
	public ParserRule getListaCursosRule() {
		return getListaCursosAccess().getRule();
	}
	
	//ListaDisciplinas:
	//	{ListaDisciplinas}
	//	'disciplinas';
	public ListaDisciplinasElements getListaDisciplinasAccess() {
		return pListaDisciplinas;
	}
	
	public ParserRule getListaDisciplinasRule() {
		return getListaDisciplinasAccess().getRule();
	}
	
	//ListaDepartamentos:
	//	departamento+=Departamento
	//	departamento+=Departamento*;
	public ListaDepartamentosElements getListaDepartamentosAccess() {
		return pListaDepartamentos;
	}
	
	public ParserRule getListaDepartamentosRule() {
		return getListaDepartamentosAccess().getRule();
	}
	
	//ListaPeriodos:
	//	periodo+=Periodo
	//	periodo+=Periodo*;
	public ListaPeriodosElements getListaPeriodosAccess() {
		return pListaPeriodos;
	}
	
	public ParserRule getListaPeriodosRule() {
		return getListaPeriodosAccess().getRule();
	}
	
	//Curso:
	//	'curso' nome=EString
	//	'{'
	//	organizacaoCurso=OrganizacaoCurso
	//	'}';
	public CursoElements getCursoAccess() {
		return pCurso;
	}
	
	public ParserRule getCursoRule() {
		return getCursoAccess().getRule();
	}
	
	//Departamento:
	//	'departamento' nome=EString
	//	'{'
	//	organizacaoDepartamento=OrganizacaoDepartamento
	//	'}';
	public DepartamentoElements getDepartamentoAccess() {
		return pDepartamento;
	}
	
	public ParserRule getDepartamentoRule() {
		return getDepartamentoAccess().getRule();
	}
	
	//Periodo:
	//	'periodo' nome=EString;
	public PeriodoElements getPeriodoAccess() {
		return pPeriodo;
	}
	
	public ParserRule getPeriodoRule() {
		return getPeriodoAccess().getRule();
	}
	
	//enum Fonte:
	//	Normal | Sans | Serif | Monospace;
	public FonteElements getFonteAccess() {
		return eFonte;
	}
	
	public EnumRule getFonteRule() {
		return getFonteAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
