/**
 * generated by Xtext 2.9.2
 */
package org.xtext.ace.acedsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ace.acedsl.ui.AbstractAceDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AceDslUiModule extends AbstractAceDslUiModule {
  public AceDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
